-- =====================================================================
-- Hoops Archive -- migration 0003h3 : cartes 2025-26-topps-three (partie 3/3)
-- FICHIER GENERE AUTOMATIQUEMENT -- ne pas editer a la main.
-- Relancable sans risque (ON CONFLICT DO UPDATE).
-- =====================================================================

begin;

-- Cartes (137)
insert into public.cards (set_id, card_code, subset, player, team, player_id, team_id, season, rookie, variant, jersey_number) values
  ('2025-26-topps-three', 'TP-7', 'PAINT', 'Devin Booker', 'Phoenix Suns', 'devin-booker', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-8', 'PAINT', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-9', 'PAINT', 'Ja Morant', 'Memphis Grizzlies', 'ja-morant', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-AB', 'TP', 'Anthony Black', 'Orlando Magic', 'anthony-black', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-AH', 'TP', 'Al Horford', 'Boston Celtics', 'al-horford', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-AJ', 'TP', 'AJ Johnson', 'Washington Wizards', 'aj-johnson', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-AM', 'TP', 'Alonzo Mourning', 'Miami Heat', 'alonzo-mourning', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-AMA', 'TP', 'Alijah Martin', 'Toronto Raptors', 'alijah-martin', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-AW', 'TP', 'Amari Williams', 'Boston Celtics', 'amari-williams', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-BB', 'TP', 'Brooks Barnhizer', 'Oklahoma City Thunder', 'brooks-barnhizer', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-BC', 'TP', 'Brandon Clarke', 'Memphis Grizzlies', 'brandon-clarke', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-CL', 'TP', 'Chaz Lanier', 'Detroit Pistons', 'chaz-lanier', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-DG', 'TP', 'Daniel Gafford', 'Dallas Mavericks', 'daniel-gafford', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-DH', 'TP', 'DaRon Holmes II', 'Denver Nuggets', 'daron-holmes-ii', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-DR', 'TP', 'Dennis Rodman', 'Chicago Bulls', 'dennis-rodman', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-DRO', 'TP', 'David Robinson', 'San Antonio Spurs', 'david-robinson', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-HO', 'TP', 'Hakeem Olajuwon', 'Houston Rockets', 'hakeem-olajuwon', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-JH', 'TP', 'Jrue Holiday', 'Boston Celtics', 'jrue-holiday', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-JJ', 'TP', 'Jaime Jaquez Jr.', 'Miami Heat', 'jaime-jaquez-jr', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-JK', 'TP', 'Jason Kidd', 'Dallas Mavericks', 'jason-kidd', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-JS', 'TP', 'Jeremy Sochan', 'San Antonio Spurs', 'jeremy-sochan', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-JSM', 'TP', 'Javon Small', 'Memphis Grizzlies', 'javon-small', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-JW', 'TP', 'Jamir Watkins', 'Washington Wizards', 'jamir-watkins', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-KB', 'TP', 'Koby Brea', 'Phoenix Suns', 'koby-brea', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-KF', 'TP', 'Kyle Filipowski', 'Utah Jazz', 'kyle-filipowski', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-KG', 'TP', 'Kyshawn George', 'Washington Wizards', 'kyshawn-george', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-KJ', 'TP', 'Kam Jones', 'Indiana Pacers', 'kam-jones', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-KM', 'TP', 'Khris Middleton', 'Washington Wizards', 'khris-middleton', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-KMU', 'TP', 'Kris Murray', 'Portland Trail Blazers', 'kris-murray', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-KW', 'TP', 'Kel''el Ware', 'Miami Heat', 'kel-el-ware', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-LM', 'TP', 'Lauri Markkanen', 'Utah Jazz', 'lauri-markkanen', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-MB', 'TP', 'Mikal Bridges', 'New York Knicks', 'mikal-bridges', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-MP', 'TP', 'Micah Peavy', 'New Orleans Pelicans', 'micah-peavy', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-MR', 'TP', 'Maxime Raynaud', 'Sacramento Kings', 'maxime-raynaud', 'sacramento-kings', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-MS', 'TP', 'Marcus Smart', 'Washington Wizards', 'marcus-smart', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-NT', 'TP', 'Nikola Topić', 'Oklahoma City Thunder', 'nikola-topic', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-PP', 'TP', 'Payton Pritchard', 'Boston Celtics', 'payton-pritchard', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-PPI', 'TP', 'Paul Pierce', 'Boston Celtics', 'paul-pierce', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-RA', 'TP', 'Ray Allen', 'Boston Celtics', 'ray-allen', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-RD', 'TP', 'Ryan Dunn', 'Phoenix Suns', 'ryan-dunn', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-RH', 'TP', 'Ronald Holland II', 'Detroit Pistons', 'ronald-holland-ii', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-TK', 'TP', 'Tyler Kolek', 'New York Knicks', 'tyler-kolek', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-TS', 'TP', 'Tidjane Salaün', 'Charlotte Hornets', 'tidjane-salaun', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-TSJ', 'TP', 'Terrence Shannon Jr.', 'Minnesota Timberwolves', 'terrence-shannon-jr', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-TSM', 'TP', 'Tyler Smith', 'Milwaukee Bucks', 'tyler-smith', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-Td', 'TP', 'Tristan da Silva', 'Orlando Magic', 'tristan-da-silva', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-VC', 'TP', 'Vince Carter', 'Toronto Raptors', 'vince-carter', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-YM', 'TP', 'Yves Missi', 'New Orleans Pelicans', 'yves-missi', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TP-ZE', 'TP', 'Zach Edey', 'Memphis Grizzlies', 'zach-edey', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-BAD', 'TRA', 'Dylan Harper / Alex Sarr / Brandon Miller', 'San Antonio Spurs / Washington Wizards / Charlotte Hornets', 'dylan-harper', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-CAG', 'TRA', 'Collin Murray-Boyles / Alijah Martin / Gradey Dick', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-CDA', 'TRA', 'Cooper Flagg / Dylan Harper / Ace Bailey', 'Dallas Mavericks / San Antonio Spurs / Utah Jazz', 'cooper-flagg', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-CKK', 'TRA', 'Cooper Flagg / Kon Knueppel / Khaman Maluach', 'Dallas Mavericks / Charlotte Hornets / Phoenix Suns', 'cooper-flagg', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-CLA', 'TRA', 'Cooper Flagg / Asa Newell / Liam McNeeley', 'Dallas Mavericks / Atlanta Hawks / Charlotte Hornets', 'cooper-flagg', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-DNE', 'TRA', 'Egor Dëmin / Nolan Traore / Drake Powell', 'Brooklyn Nets', 'egor-demin', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-JBT', 'TRA', 'Tyrese Haliburton / Jarace Walker / Bennedict Mathurin', 'Indiana Pacers', 'tyrese-haliburton', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-JPC', 'TRA', 'Cooper Flagg / Jayson Tatum / Paolo Banchero', 'Dallas Mavericks / Boston Celtics / Orlando Magic', 'cooper-flagg', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-JZC', 'TRA', 'Cedric Coward / Zach Edey / Jaren Jackson Jr.', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-NYN', 'TRA', 'Noa Essengue / Nolan Traore / Yang Hansen', 'Chicago Bulls / Brooklyn Nets / Portland Trail Blazers', 'noa-essengue', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-OZA', 'TRA', 'Asa Newell / Zaccharie Risacher / Onyeka Okongwu', 'Atlanta Hawks', 'asa-newell', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-SJZ', 'TRA', 'Stephon Castle / Jaime Jaquez Jr. / Zach Lavine', 'San Antonio Spurs / Miami Heat / Sacramento Kings', 'stephon-castle', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-SKJ', 'TRA', 'Jayson Tatum / Kevin Durant / Stephen Curry', 'Boston Celtics / Phoenix Suns / Golden State Warriors', 'jayson-tatum', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-SPK', 'TRA', 'Stephon Castle / Paolo Banchero / Kevin Durant', 'San Antonio Spurs / Orlando Magic / Phoenix Suns', 'stephon-castle', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-TMD', 'TRA', 'Dylan Harper / Tony Parker / Manu Ginobili', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-WCA', 'TRA', 'Walter Clayton Jr. / Alijah Martin / Chaz Lanier', 'Utah Jazz / Toronto Raptors / Detroit Pistons', 'walter-clayton-jr', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'TRA-WKN', 'TRA', 'Nolan Traore / Walter Clayton Jr. / Kasparas Jakučionis', 'Brooklyn Nets / Utah Jazz / Miami Heat', 'nolan-traore', null, '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-AB', 'V3A', 'Anthony Black', 'Orlando Magic', 'anthony-black', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-AD', 'V3A', 'Ayo Dosunmu', 'Chicago Bulls', 'ayo-dosunmu', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-AG', 'V3A', 'Aaron Gordon', 'Denver Nuggets', 'aaron-gordon', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-AM', 'V3A', 'Ajay Mitchell', 'Oklahoma City Thunder', 'ajay-mitchell', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-AS', 'V3A', 'Alex Sarr', 'Washington Wizards', 'alex-sarr', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-BC', 'V3A', 'Bilal Coulibaly', 'Washington Wizards', 'bilal-coulibaly', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-BM', 'V3A', 'Brandon Miller', 'Charlotte Hornets', 'brandon-miller', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-BRJ', 'V3A', 'Bronny James', 'Los Angeles Lakers', 'bronny-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-BSH', 'V3A', 'Ben Sheppard', 'Indiana Pacers', 'ben-sheppard', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-CH', 'V3A', 'Chet Holmgren', 'Oklahoma City Thunder', 'chet-holmgren', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-CJ', 'V3A', 'Cameron Johnson', 'Brooklyn Nets', 'cameron-johnson', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-CM', 'V3A', 'CJ McCollum', 'New Orleans Pelicans', 'cj-mccollum', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-CP', 'V3A', 'Chris Paul', 'San Antonio Spurs', 'chris-paul', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-CW', 'V3A', 'Cam Whitmore', 'Houston Rockets', 'cam-whitmore', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-CWI', 'V3A', 'Cody Williams', 'Utah Jazz', 'cody-williams', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-DG', 'V3A', 'Daniel Gafford', 'Dallas Mavericks', 'daniel-gafford', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-DL', 'V3A', 'Dereck Lively II', 'Dallas Mavericks', 'dereck-lively-ii', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-DMI', 'V3A', 'Donovan Mitchell', 'Cleveland Cavaliers', 'donovan-mitchell', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-DR', 'V3A', 'D''Angelo Russell', 'Brooklyn Nets', 'd-angelo-russell', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-DV', 'V3A', 'Devin Vassell', 'San Antonio Spurs', 'devin-vassell', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-DW', 'V3A', 'Derrick White', 'Boston Celtics', 'derrick-white', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-FW', 'V3A', 'Franz Wagner', 'Orlando Magic', 'franz-wagner', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-GA', 'V3A', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-GD', 'V3A', 'Gradey Dick', 'Toronto Raptors', 'gradey-dick', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-GT', 'V3A', 'Gary Trent Jr.', 'Milwaukee Bucks', 'gary-trent-jr', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-HJ', 'V3A', 'Herbert Jones', 'New Orleans Pelicans', 'herbert-jones', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-IC', 'V3A', 'Isaiah Collier', 'Utah Jazz', 'isaiah-collier', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JA', 'V3A', 'Jarrett Allen', 'Cleveland Cavaliers', 'jarrett-allen', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JB', 'V3A', 'Jalen Brunson', 'New York Knicks', 'jalen-brunson', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JH', 'V3A', 'James Harden', 'Los Angeles Clippers', 'james-harden', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JHA', 'V3A', 'Jordan Hawkins', 'New Orleans Pelicans', 'jordan-hawkins', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JHO', 'V3A', 'Jrue Holiday', 'Boston Celtics', 'jrue-holiday', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JJ', 'V3A', 'Jaime Jaquez Jr.', 'Miami Heat', 'jaime-jaquez-jr', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JJJ', 'V3A', 'Jaren Jackson Jr.', 'Memphis Grizzlies', 'jaren-jackson-jr', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JM', 'V3A', 'Jamal Murray', 'Denver Nuggets', 'jamal-murray', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JT', 'V3A', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-JW', 'V3A', 'Jalen Williams', 'Oklahoma City Thunder', 'jalen-williams', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-KF', 'V3A', 'Kyle Filipowski', 'Utah Jazz', 'kyle-filipowski', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-KP', 'V3A', 'Kristaps Porzingis', 'Boston Celtics', 'kristaps-porzingis', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-KW', 'V3A', 'Kel''el Ware', 'Miami Heat', 'kel-el-ware', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-LJ', 'V3A', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-LM', 'V3A', 'Lauri Markkanen', 'Utah Jazz', 'lauri-markkanen', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-MB', 'V3A', 'Mikal Bridges', 'New York Knicks', 'mikal-bridges', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-MP', 'V3A', 'Michael Porter Jr.', 'Denver Nuggets', 'michael-porter-jr', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-MT', 'V3A', 'Myles Turner', 'Indiana Pacers', 'myles-turner', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-NC', 'V3A', 'Nic Claxton', 'Brooklyn Nets', 'nic-claxton', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-OA', 'V3A', 'OG Anunoby', 'New York Knicks', 'og-anunoby', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-OT', 'V3A', 'Obi Toppin', 'Indiana Pacers', 'obi-toppin', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-PB', 'V3A', 'Paolo Banchero', 'Orlando Magic', 'paolo-banchero', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-PP', 'V3A', 'Payton Pritchard', 'Boston Celtics', 'payton-pritchard', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-RD', 'V3A', 'Ryan Dunn', 'Phoenix Suns', 'ryan-dunn', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-RDI', 'V3A', 'Rob Dillingham', 'Minnesota Timberwolves', 'rob-dillingham', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-RG', 'V3A', 'Rudy Gobert', 'Minnesota Timberwolves', 'rudy-gobert', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-RH', 'V3A', 'Ronald Holland II', 'Detroit Pistons', 'ronald-holland-ii', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-SC', 'V3A', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-SCA', 'V3A', 'Stephon Castle', 'San Antonio Spurs', 'stephon-castle', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-SGA', 'V3A', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-SH', 'V3A', 'Scoot Henderson', 'Portland Trail Blazers', 'scoot-henderson', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-SS', 'V3A', 'Shaedon Sharpe', 'Portland Trail Blazers', 'shaedon-sharpe', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-TDS', 'V3A', 'Tristan da Silva', 'Orlando Magic', 'tristan-da-silva', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-THA', 'V3A', 'Tyrese Haliburton', 'Indiana Pacers', 'tyrese-haliburton', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-THD', 'V3A', 'Taylor Hendricks', 'Utah Jazz', 'taylor-hendricks', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-TM', 'V3A', 'Tyrese Maxey', 'Philadelphia 76ers', 'tyrese-maxey', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-TS', 'V3A', 'Tyler Smith', 'Milwaukee Bucks', 'tyler-smith', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-TSA', 'V3A', 'Tidjane Salaün', 'Charlotte Hornets', 'tidjane-salaun', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-TSJ', 'V3A', 'Terrence Shannon Jr.', 'Minnesota Timberwolves', 'terrence-shannon-jr', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-VW', 'V3A', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-WK', 'V3A', 'Walker Kessler', 'Utah Jazz', 'walker-kessler', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-YM', 'V3A', 'Yves Missi', 'New Orleans Pelicans', 'yves-missi', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-ZE', 'V3A', 'Zach Edey', 'Memphis Grizzlies', 'zach-edey', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-three', 'V3A-ZR', 'V3A', 'Zaccharie Risacher', 'Atlanta Hawks', 'zaccharie-risacher', 'atlanta-hawks', '2025-26', false, null, null)
on conflict (set_id, card_code) do update set
  subset = excluded.subset, player = excluded.player, team = excluded.team,
  player_id = excluded.player_id, team_id = excluded.team_id, season = excluded.season,
  rookie = excluded.rookie, variant = excluded.variant, jersey_number = excluded.jersey_number;

-- Associations carte/joueur (171)
insert into public.card_players (set_id, card_code, slot, player, player_id, team, team_id, season) values
  ('2025-26-topps-three', 'TP-7', 1, 'Devin Booker', 'devin-booker', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-three', 'TP-8', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-three', 'TP-9', 1, 'Ja Morant', 'ja-morant', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-three', 'TP-AB', 1, 'Anthony Black', 'anthony-black', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-three', 'TP-AH', 1, 'Al Horford', 'al-horford', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'TP-AJ', 1, 'AJ Johnson', 'aj-johnson', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-three', 'TP-AM', 1, 'Alonzo Mourning', 'alonzo-mourning', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-three', 'TP-AMA', 1, 'Alijah Martin', 'alijah-martin', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-three', 'TP-AW', 1, 'Amari Williams', 'amari-williams', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'TP-BB', 1, 'Brooks Barnhizer', 'brooks-barnhizer', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-three', 'TP-BC', 1, 'Brandon Clarke', 'brandon-clarke', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-three', 'TP-CL', 1, 'Chaz Lanier', 'chaz-lanier', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-three', 'TP-DG', 1, 'Daniel Gafford', 'daniel-gafford', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-three', 'TP-DH', 1, 'DaRon Holmes II', 'daron-holmes-ii', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-three', 'TP-DR', 1, 'Dennis Rodman', 'dennis-rodman', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-three', 'TP-DRO', 1, 'David Robinson', 'david-robinson', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'TP-HO', 1, 'Hakeem Olajuwon', 'hakeem-olajuwon', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-three', 'TP-JH', 1, 'Jrue Holiday', 'jrue-holiday', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'TP-JJ', 1, 'Jaime Jaquez Jr.', 'jaime-jaquez-jr', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-three', 'TP-JK', 1, 'Jason Kidd', 'jason-kidd', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-three', 'TP-JS', 1, 'Jeremy Sochan', 'jeremy-sochan', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'TP-JSM', 1, 'Javon Small', 'javon-small', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-three', 'TP-JW', 1, 'Jamir Watkins', 'jamir-watkins', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-three', 'TP-KB', 1, 'Koby Brea', 'koby-brea', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-three', 'TP-KF', 1, 'Kyle Filipowski', 'kyle-filipowski', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'TP-KG', 1, 'Kyshawn George', 'kyshawn-george', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-three', 'TP-KJ', 1, 'Kam Jones', 'kam-jones', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-three', 'TP-KM', 1, 'Khris Middleton', 'khris-middleton', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-three', 'TP-KMU', 1, 'Kris Murray', 'kris-murray', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-three', 'TP-KW', 1, 'Kel''el Ware', 'kel-el-ware', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-three', 'TP-LM', 1, 'Lauri Markkanen', 'lauri-markkanen', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'TP-MB', 1, 'Mikal Bridges', 'mikal-bridges', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-three', 'TP-MP', 1, 'Micah Peavy', 'micah-peavy', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-three', 'TP-MR', 1, 'Maxime Raynaud', 'maxime-raynaud', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-three', 'TP-MS', 1, 'Marcus Smart', 'marcus-smart', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-three', 'TP-NT', 1, 'Nikola Topić', 'nikola-topic', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-three', 'TP-PP', 1, 'Payton Pritchard', 'payton-pritchard', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'TP-PPI', 1, 'Paul Pierce', 'paul-pierce', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'TP-RA', 1, 'Ray Allen', 'ray-allen', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'TP-RD', 1, 'Ryan Dunn', 'ryan-dunn', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-three', 'TP-RH', 1, 'Ronald Holland II', 'ronald-holland-ii', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-three', 'TP-TK', 1, 'Tyler Kolek', 'tyler-kolek', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-three', 'TP-TS', 1, 'Tidjane Salaün', 'tidjane-salaun', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-three', 'TP-TSJ', 1, 'Terrence Shannon Jr.', 'terrence-shannon-jr', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-three', 'TP-TSM', 1, 'Tyler Smith', 'tyler-smith', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-three', 'TP-Td', 1, 'Tristan da Silva', 'tristan-da-silva', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-three', 'TP-VC', 1, 'Vince Carter', 'vince-carter', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-three', 'TP-YM', 1, 'Yves Missi', 'yves-missi', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-three', 'TP-ZE', 1, 'Zach Edey', 'zach-edey', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-three', 'TRA-BAD', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'TRA-BAD', 2, 'Alex Sarr', 'alex-sarr', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-three', 'TRA-BAD', 3, 'Brandon Miller', 'brandon-miller', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-three', 'TRA-CAG', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-three', 'TRA-CAG', 2, 'Alijah Martin', 'alijah-martin', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-three', 'TRA-CAG', 3, 'Gradey Dick', 'gradey-dick', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-three', 'TRA-CDA', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-three', 'TRA-CDA', 2, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'TRA-CDA', 3, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'TRA-CKK', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-three', 'TRA-CKK', 2, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-three', 'TRA-CKK', 3, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-three', 'TRA-CLA', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-three', 'TRA-CLA', 2, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-three', 'TRA-CLA', 3, 'Liam McNeeley', 'liam-mcneeley', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-three', 'TRA-DNE', 1, 'Egor Dëmin', 'egor-demin', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-three', 'TRA-DNE', 2, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-three', 'TRA-DNE', 3, 'Drake Powell', 'drake-powell', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-three', 'TRA-JBT', 1, 'Tyrese Haliburton', 'tyrese-haliburton', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-three', 'TRA-JBT', 2, 'Jarace Walker', 'jarace-walker', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-three', 'TRA-JBT', 3, 'Bennedict Mathurin', 'bennedict-mathurin', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-three', 'TRA-JPC', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-three', 'TRA-JPC', 2, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'TRA-JPC', 3, 'Paolo Banchero', 'paolo-banchero', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-three', 'TRA-JZC', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-three', 'TRA-JZC', 2, 'Zach Edey', 'zach-edey', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-three', 'TRA-JZC', 3, 'Jaren Jackson Jr.', 'jaren-jackson-jr', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-three', 'TRA-NYN', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-three', 'TRA-NYN', 2, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-three', 'TRA-NYN', 3, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-three', 'TRA-OZA', 1, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-three', 'TRA-OZA', 2, 'Zaccharie Risacher', 'zaccharie-risacher', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-three', 'TRA-OZA', 3, 'Onyeka Okongwu', 'onyeka-okongwu', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-three', 'TRA-SJZ', 1, 'Stephon Castle', 'stephon-castle', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'TRA-SJZ', 2, 'Jaime Jaquez Jr.', 'jaime-jaquez-jr', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-three', 'TRA-SJZ', 3, 'Zach Lavine', 'zach-lavine', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-three', 'TRA-SKJ', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'TRA-SKJ', 2, 'Kevin Durant', 'kevin-durant', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-three', 'TRA-SKJ', 3, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-three', 'TRA-SPK', 1, 'Stephon Castle', 'stephon-castle', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'TRA-SPK', 2, 'Paolo Banchero', 'paolo-banchero', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-three', 'TRA-SPK', 3, 'Kevin Durant', 'kevin-durant', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-three', 'TRA-TMD', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'TRA-TMD', 2, 'Tony Parker', 'tony-parker', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'TRA-TMD', 3, 'Manu Ginobili', 'manu-ginobili', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'TRA-WCA', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'TRA-WCA', 2, 'Alijah Martin', 'alijah-martin', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-three', 'TRA-WCA', 3, 'Chaz Lanier', 'chaz-lanier', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-three', 'TRA-WKN', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-three', 'TRA-WKN', 2, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'TRA-WKN', 3, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-three', 'V3A-AB', 1, 'Anthony Black', 'anthony-black', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-three', 'V3A-AD', 1, 'Ayo Dosunmu', 'ayo-dosunmu', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-three', 'V3A-AG', 1, 'Aaron Gordon', 'aaron-gordon', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-three', 'V3A-AM', 1, 'Ajay Mitchell', 'ajay-mitchell', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-three', 'V3A-AS', 1, 'Alex Sarr', 'alex-sarr', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-three', 'V3A-BC', 1, 'Bilal Coulibaly', 'bilal-coulibaly', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-three', 'V3A-BM', 1, 'Brandon Miller', 'brandon-miller', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-three', 'V3A-BRJ', 1, 'Bronny James', 'bronny-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-three', 'V3A-BSH', 1, 'Ben Sheppard', 'ben-sheppard', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-three', 'V3A-CH', 1, 'Chet Holmgren', 'chet-holmgren', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-three', 'V3A-CJ', 1, 'Cameron Johnson', 'cameron-johnson', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-three', 'V3A-CM', 1, 'CJ McCollum', 'cj-mccollum', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-three', 'V3A-CP', 1, 'Chris Paul', 'chris-paul', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'V3A-CW', 1, 'Cam Whitmore', 'cam-whitmore', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-three', 'V3A-CWI', 1, 'Cody Williams', 'cody-williams', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'V3A-DG', 1, 'Daniel Gafford', 'daniel-gafford', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-three', 'V3A-DL', 1, 'Dereck Lively II', 'dereck-lively-ii', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-three', 'V3A-DMI', 1, 'Donovan Mitchell', 'donovan-mitchell', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-three', 'V3A-DR', 1, 'D''Angelo Russell', 'd-angelo-russell', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-three', 'V3A-DV', 1, 'Devin Vassell', 'devin-vassell', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'V3A-DW', 1, 'Derrick White', 'derrick-white', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'V3A-FW', 1, 'Franz Wagner', 'franz-wagner', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-three', 'V3A-GA', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-three', 'V3A-GD', 1, 'Gradey Dick', 'gradey-dick', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-three', 'V3A-GT', 1, 'Gary Trent Jr.', 'gary-trent-jr', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-three', 'V3A-HJ', 1, 'Herbert Jones', 'herbert-jones', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-three', 'V3A-IC', 1, 'Isaiah Collier', 'isaiah-collier', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'V3A-JA', 1, 'Jarrett Allen', 'jarrett-allen', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-three', 'V3A-JB', 1, 'Jalen Brunson', 'jalen-brunson', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-three', 'V3A-JH', 1, 'James Harden', 'james-harden', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-three', 'V3A-JHA', 1, 'Jordan Hawkins', 'jordan-hawkins', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-three', 'V3A-JHO', 1, 'Jrue Holiday', 'jrue-holiday', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'V3A-JJ', 1, 'Jaime Jaquez Jr.', 'jaime-jaquez-jr', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-three', 'V3A-JJJ', 1, 'Jaren Jackson Jr.', 'jaren-jackson-jr', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-three', 'V3A-JM', 1, 'Jamal Murray', 'jamal-murray', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-three', 'V3A-JT', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'V3A-JW', 1, 'Jalen Williams', 'jalen-williams', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-three', 'V3A-KF', 1, 'Kyle Filipowski', 'kyle-filipowski', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'V3A-KP', 1, 'Kristaps Porzingis', 'kristaps-porzingis', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'V3A-KW', 1, 'Kel''el Ware', 'kel-el-ware', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-three', 'V3A-LJ', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-three', 'V3A-LM', 1, 'Lauri Markkanen', 'lauri-markkanen', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'V3A-MB', 1, 'Mikal Bridges', 'mikal-bridges', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-three', 'V3A-MP', 1, 'Michael Porter Jr.', 'michael-porter-jr', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-three', 'V3A-MT', 1, 'Myles Turner', 'myles-turner', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-three', 'V3A-NC', 1, 'Nic Claxton', 'nic-claxton', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-three', 'V3A-OA', 1, 'OG Anunoby', 'og-anunoby', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-three', 'V3A-OT', 1, 'Obi Toppin', 'obi-toppin', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-three', 'V3A-PB', 1, 'Paolo Banchero', 'paolo-banchero', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-three', 'V3A-PP', 1, 'Payton Pritchard', 'payton-pritchard', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-three', 'V3A-RD', 1, 'Ryan Dunn', 'ryan-dunn', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-three', 'V3A-RDI', 1, 'Rob Dillingham', 'rob-dillingham', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-three', 'V3A-RG', 1, 'Rudy Gobert', 'rudy-gobert', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-three', 'V3A-RH', 1, 'Ronald Holland II', 'ronald-holland-ii', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-three', 'V3A-SC', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-three', 'V3A-SCA', 1, 'Stephon Castle', 'stephon-castle', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'V3A-SGA', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-three', 'V3A-SH', 1, 'Scoot Henderson', 'scoot-henderson', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-three', 'V3A-SS', 1, 'Shaedon Sharpe', 'shaedon-sharpe', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-three', 'V3A-TDS', 1, 'Tristan da Silva', 'tristan-da-silva', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-three', 'V3A-THA', 1, 'Tyrese Haliburton', 'tyrese-haliburton', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-three', 'V3A-THD', 1, 'Taylor Hendricks', 'taylor-hendricks', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'V3A-TM', 1, 'Tyrese Maxey', 'tyrese-maxey', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-three', 'V3A-TS', 1, 'Tyler Smith', 'tyler-smith', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-three', 'V3A-TSA', 1, 'Tidjane Salaün', 'tidjane-salaun', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-three', 'V3A-TSJ', 1, 'Terrence Shannon Jr.', 'terrence-shannon-jr', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-three', 'V3A-VW', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-three', 'V3A-WK', 1, 'Walker Kessler', 'walker-kessler', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-three', 'V3A-YM', 1, 'Yves Missi', 'yves-missi', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-three', 'V3A-ZE', 1, 'Zach Edey', 'zach-edey', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-three', 'V3A-ZR', 1, 'Zaccharie Risacher', 'zaccharie-risacher', 'Atlanta Hawks', 'atlanta-hawks', '2025-26')
on conflict (set_id, card_code, slot) do update set
  player = excluded.player, player_id = excluded.player_id, team = excluded.team,
  team_id = excluded.team_id, season = excluded.season;

commit;
