-- =====================================================================
-- Hoops Archive -- migration 0003d3 : cartes 2025-26-topps-chrome (partie 3/3)
-- FICHIER GENERE AUTOMATIQUEMENT -- ne pas editer a la main.
-- Relancable sans risque (ON CONFLICT DO UPDATE).
-- =====================================================================

begin;

-- Cartes (250)
insert into public.cards (set_id, card_code, subset, player, team, player_id, team_id, season, rookie, variant, jersey_number) values
  ('2025-26-topps-chrome', 'SY-13', 'SY', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'SY-14', 'SY', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'SY-15', 'SY', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'SY-2', 'SY', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'SY-3', 'SY', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'SY-4', 'SY', 'Anthony Edwards', 'Minnesota Timberwolves', 'anthony-edwards', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'SY-5', 'SY', 'Paolo Banchero', 'Orlando Magic', 'paolo-banchero', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'SY-6', 'SY', 'Kyrie Irving', 'Dallas Mavericks', 'kyrie-irving', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'SY-7', 'SY', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'SY-8', 'SY', 'LaMelo Ball', 'Charlotte Hornets', 'lamelo-ball', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'SY-9', 'SY', 'Magic Johnson', 'Los Angeles Lakers', 'magic-johnson', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAIR-AB', 'TAIR', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-AN', 'TAIR', 'Asa Newell', 'Atlanta Hawks', 'asa-newell', 'atlanta-hawks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-BS', 'TAIR', 'Ben Saraf', 'Brooklyn Nets', 'ben-saraf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-CC', 'TAIR', 'Cedric Coward', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-CF', 'TAIR', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-CMB', 'TAIR', 'Collin Murray-Boyles', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-DH', 'TAIR', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-DP', 'TAIR', 'Drake Powell', 'Brooklyn Nets', 'drake-powell', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-DQ', 'TAIR', 'Derik Queen', 'New Orleans Pelicans', 'derik-queen', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-DW', 'TAIR', 'Danny Wolf', 'Brooklyn Nets', 'danny-wolf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-ED', 'TAIR', 'Egor Dëmin', 'Brooklyn Nets', 'egor-demin', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-JB', 'TAIR', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-JR', 'TAIR', 'Jase Richardson', 'Orlando Magic', 'jase-richardson', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-KJ', 'TAIR', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-KK', 'TAIR', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-KM', 'TAIR', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-KS', 'TAIR', 'Kobe Sanders', 'Los Angeles Clippers', 'kobe-sanders', 'los-angeles-clippers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-LMC', 'TAIR', 'Liam McNeeley', 'Charlotte Hornets', 'liam-mcneeley', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-NC', 'TAIR', 'Nique Clifford', 'Sacramento Kings', 'nique-clifford', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-NE', 'TAIR', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-NP', 'TAIR', 'Noah Penda', 'Orlando Magic', 'noah-penda', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-NT', 'TAIR', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-RF', 'TAIR', 'Rasheer Fleming', 'Phoenix Suns', 'rasheer-fleming', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-TP', 'TAIR', 'Tyrese Proctor', 'Cleveland Cavaliers', 'tyrese-proctor', 'cleveland-cavaliers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-TS', 'TAIR', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-WCJ', 'TAIR', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-WIR', 'TAIR', 'Will Richard', 'Golden State Warriors', 'will-richard', 'golden-state-warriors', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-WR', 'TAIR', 'Will Riley', 'Washington Wizards', 'will-riley', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-YH', 'TAIR', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAIR-YKN', 'TAIR', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers', 'yanic-konan-niederhauser', 'los-angeles-clippers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAU-AB', 'TAU', 'Anthony Black', 'Orlando Magic', 'anthony-black', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-AC', 'TAU', 'Alex Caruso', 'Oklahoma City Thunder', 'alex-caruso', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-AG', 'TAU', 'Aaron Gordon', 'Denver Nuggets', 'aaron-gordon', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-AJJ', 'TAU', 'AJ Johnson', 'Washington Wizards', 'aj-johnson', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-BSC', 'TAU', 'Baylor Scheierman', 'Boston Celtics', 'baylor-scheierman', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-CA', 'TAU', 'Cole Anthony', 'Orlando Magic', 'cole-anthony', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-CC', 'TAU', 'Clint Capela', 'Atlanta Hawks', 'clint-capela', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-CJM', 'TAU', 'CJ McCollum', 'New Orleans Pelicans', 'cj-mccollum', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-CL', 'TAU', 'Christian Laettner', 'Atlanta Hawks', 'christian-laettner', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-CW', 'TAU', 'Cam Whitmore', 'Houston Rockets', 'cam-whitmore', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-DH', 'TAU', 'Dwight Howard', 'Orlando Magic', 'dwight-howard', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-DJM', 'TAU', 'Dejounte Murray', 'New Orleans Pelicans', 'dejounte-murray', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-DL', 'TAU', 'Dereck Lively II', 'Dallas Mavericks', 'dereck-lively-ii', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-DM', 'TAU', 'Davion Mitchell', 'Miami Heat', 'davion-mitchell', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-DT', 'TAU', 'David Thompson', 'Denver Nuggets', 'david-thompson', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-DW', 'TAU', 'Derrick White', 'Boston Celtics', 'derrick-white', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-FVV', 'TAU', 'Fred VanVleet', 'Houston Rockets', 'fred-vanvleet', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-GD', 'TAU', 'Gradey Dick', 'Toronto Raptors', 'gradey-dick', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-JC', 'TAU', 'Jaylen Clark', 'Minnesota Timberwolves', 'jaylen-clark', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-JF', 'TAU', 'Johnny Furphy', 'Indiana Pacers', 'johnny-furphy', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-JH', 'TAU', 'Jordan Hawkins', 'New Orleans Pelicans', 'jordan-hawkins', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-JS', 'TAU', 'Jamal Shead', 'Toronto Raptors', 'jamal-shead', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-JSO', 'TAU', 'Jeremy Sochan', 'San Antonio Spurs', 'jeremy-sochan', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-JT', 'TAU', 'Jaylon Tyson', 'Cleveland Cavaliers', 'jaylon-tyson', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-JTM', 'TAU', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-KK', 'TAU', 'Kyle Kuzma', 'Milwaukee Bucks', 'kyle-kuzma', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-KYG', 'TAU', 'Kyshawn George', 'Washington Wizards', 'kyshawn-george', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-OBI', 'TAU', 'Obi Toppin', 'Indiana Pacers', 'obi-toppin', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-PG', 'TAU', 'Pau Gasol', 'Los Angeles Lakers', 'pau-gasol', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-PPR', 'TAU', 'Payton Pritchard', 'Boston Celtics', 'payton-pritchard', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-PS', 'TAU', 'Peja Stojaković', 'Sacramento Kings', 'peja-stojakovic', 'sacramento-kings', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-RD', 'TAU', 'Ryan Dunn', 'Phoenix Suns', 'ryan-dunn', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-RHA', 'TAU', 'Rui Hachimura', 'Los Angeles Lakers', 'rui-hachimura', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-SC', 'TAU', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-SH', 'TAU', 'Scoot Henderson', 'Portland Trail Blazers', 'scoot-henderson', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-TSJ', 'TAU', 'Terrence Shannon Jr.', 'Minnesota Timberwolves', 'terrence-shannon-jr', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-WK', 'TAU', 'Walker Kessler', 'Utah Jazz', 'walker-kessler', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAU-ZL', 'TAU', 'Zach LaVine', 'Sacramento Kings', 'zach-lavine', 'sacramento-kings', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TAUR2-AB', 'TAIR', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-AN', 'TAIR', 'Asa Newell', 'Atlanta Hawks', 'asa-newell', 'atlanta-hawks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-BS', 'TAIR', 'Ben Saraf', 'Brooklyn Nets', 'ben-saraf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-CC', 'TAIR', 'Cedric Coward', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-CMB', 'TAIR', 'Collin Murray-Boyles', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-DH', 'TAIR', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-DP', 'TAIR', 'Drake Powell', 'Brooklyn Nets', 'drake-powell', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-DQ', 'TAIR', 'Derik Queen', 'New Orleans Pelicans', 'derik-queen', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-DW', 'TAIR', 'Danny Wolf', 'Brooklyn Nets', 'danny-wolf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-ED', 'TAIR', 'Egor Dëmin', 'Brooklyn Nets', 'egor-demin', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-JB', 'TAIR', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-JR', 'TAIR', 'Jase Richardson', 'Orlando Magic', 'jase-richardson', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-KJ', 'TAIR', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-KK', 'TAIR', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-KM', 'TAIR', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-LMC', 'TAIR', 'Liam McNeeley', 'Charlotte Hornets', 'liam-mcneeley', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-NC', 'TAIR', 'Nique Clifford', 'Sacramento Kings', 'nique-clifford', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-NE', 'TAIR', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-NT', 'TAIR', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-TP', 'TAIR', 'Tyrese Proctor', 'Cleveland Cavaliers', 'tyrese-proctor', 'cleveland-cavaliers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-TS', 'TAIR', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-WCJ', 'TAIR', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-WIR', 'TAIR', 'Will Richard', 'Golden State Warriors', 'will-richard', 'golden-state-warriors', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-WR', 'TAIR', 'Will Riley', 'Washington Wizards', 'will-riley', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TAUR2-YH', 'TAIR', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCA-AI', 'TCA', 'Allen Iverson', 'Philadelphia 76ers', 'allen-iverson', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-AS', 'TCA', 'Alex Sarr', 'Washington Wizards', 'alex-sarr', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-CH', 'TCA', 'Chet Holmgren', 'Oklahoma City Thunder', 'chet-holmgren', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-DM', 'TCA', 'Donovan Mitchell', 'Cleveland Cavaliers', 'donovan-mitchell', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-DN', 'TCA', 'Dirk Nowitzki', 'Dallas Mavericks', 'dirk-nowitzki', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-DW', 'TCA', 'Dwyane Wade', 'Miami Heat', 'dwyane-wade', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-JB', 'TCA', 'Jalen Brunson', 'New York Knicks', 'jalen-brunson', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-JG', 'TCA', 'Jalen Green', 'Houston Rockets', 'jalen-green', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-JH', 'TCA', 'James Harden', 'Los Angeles Clippers', 'james-harden', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-JM', 'TCA', 'Jamal Murray', 'Denver Nuggets', 'jamal-murray', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-JT', 'TCA', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-KD', 'TCA', 'Kevin Durant', 'Houston Rockets', 'kevin-durant', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-KG', 'TCA', 'Kevin Garnett', 'Boston Celtics', 'kevin-garnett', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-LB', 'TCA', 'Larry Bird', 'Boston Celtics', 'larry-bird', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-LBJ', 'TCA', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-MJ', 'TCA', 'Magic Johnson', 'Los Angeles Lakers', 'magic-johnson', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-PB', 'TCA', 'Paolo Banchero', 'Orlando Magic', 'paolo-banchero', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-SC', 'TCA', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-SGA', 'TCA', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-SO', 'TCA', 'Shaquille O''Neal', 'Los Angeles Lakers', 'shaquille-o-neal', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-TH', 'TCA', 'Tyrese Haliburton', 'Indiana Pacers', 'tyrese-haliburton', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-TM', 'TCA', 'Tracy McGrady', 'Orlando Magic', 'tracy-mcgrady', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-VC', 'TCA', 'Vince Carter', 'Toronto Raptors', 'vince-carter', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA-VW', 'TCA', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCA2-NJ', 'TCA2', 'Nikola Jokić', 'Denver Nuggets', 'nikola-jokic', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCAR-AB', 'TCAR', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-AM', 'TCAR', 'Alijah Martin', 'Toronto Raptors', 'alijah-martin', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-AN', 'TCAR', 'Asa Newell', 'Atlanta Hawks', 'asa-newell', 'atlanta-hawks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-AT', 'TCAR', 'Adou Thiero', 'Los Angeles Lakers', 'adou-thiero', 'los-angeles-lakers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-BS', 'TCAR', 'Ben Saraf', 'Brooklyn Nets', 'ben-saraf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-CC', 'TCAR', 'Cedric Coward', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-CF', 'TCAR', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-CL', 'TCAR', 'Chaz Lanier', 'Detroit Pistons', 'chaz-lanier', 'detroit-pistons', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-CMB', 'TCAR', 'Collin Murray-Boyles', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-DH', 'TCAR', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-DP', 'TCAR', 'Drake Powell', 'Brooklyn Nets', 'drake-powell', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-DQ', 'TCAR', 'Derik Queen', 'New Orleans Pelicans', 'derik-queen', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-DW', 'TCAR', 'Danny Wolf', 'Brooklyn Nets', 'danny-wolf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-ED', 'TCAR', 'Egor Dëmin', 'Brooklyn Nets', 'egor-demin', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-JB', 'TCAR', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-JBE', 'TCAR', 'Johni Broome', 'Philadelphia 76ers', 'johni-broome', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-JR', 'TCAR', 'Jase Richardson', 'Orlando Magic', 'jase-richardson', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-KAJ', 'TCAR', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-KB', 'TCAR', 'Koby Brea', 'Phoenix Suns', 'koby-brea', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-KJ', 'TCAR', 'Kam Jones', 'Indiana Pacers', 'kam-jones', 'indiana-pacers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-KK', 'TCAR', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-KM', 'TCAR', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-KS', 'TCAR', 'Kobe Sanders', 'Los Angeles Clippers', 'kobe-sanders', 'los-angeles-clippers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-LM', 'TCAR', 'Liam McNeeley', 'Charlotte Hornets', 'liam-mcneeley', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-MP', 'TCAR', 'Micah Peavy', 'New Orleans Pelicans', 'micah-peavy', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-MR', 'TCAR', 'Maxime Raynaud', 'Sacramento Kings', 'maxime-raynaud', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-NC', 'TCAR', 'Nique Clifford', 'Sacramento Kings', 'nique-clifford', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-NE', 'TCAR', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-NP', 'TCAR', 'Noah Penda', 'Orlando Magic', 'noah-penda', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-NT', 'TCAR', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-RF', 'TCAR', 'Rasheer Fleming', 'Phoenix Suns', 'rasheer-fleming', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-RK', 'TCAR', 'Ryan Kalkbrenner', 'Charlotte Hornets', 'ryan-kalkbrenner', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-SJ', 'TCAR', 'Sion James', 'Charlotte Hornets', 'sion-james', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-TP', 'TCAR', 'Tyrese Proctor', 'Cleveland Cavaliers', 'tyrese-proctor', 'cleveland-cavaliers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-TS', 'TCAR', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-WCJ', 'TCAR', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-WIR', 'TCAR', 'Will Richard', 'Golden State Warriors', 'will-richard', 'golden-state-warriors', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-WR', 'TCAR', 'Will Riley', 'Washington Wizards', 'will-riley', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-YH', 'TCAR', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCAR-YKN', 'TCAR', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers', 'yanic-konan-niederhauser', 'los-angeles-clippers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TCGL-1', 'TCGL', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCGL-2', 'TCGL', 'Stephon Castle', 'San Antonio Spurs', 'stephon-castle', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCGL-3', 'TCGL', 'Evan Mobley', 'Cleveland Cavaliers', 'evan-mobley', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCGR-1', 'TCGR', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCGR-2', 'TCGR', 'Stephon Castle', 'San Antonio Spurs', 'stephon-castle', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TCGR-3', 'TCGR', 'Evan Mobley', 'Cleveland Cavaliers', 'evan-mobley', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-1', 'TT', 'Nikola Jokić', 'Denver Nuggets', 'nikola-jokic', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-10', 'TT', 'Karl-Anthony Towns', 'New York Knicks', 'karl-anthony-towns', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-11', 'TT', 'Shaquille O''Neal', 'Los Angeles Lakers', 'shaquille-o-neal', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-12', 'TT', 'Hakeem Olajuwon', 'Houston Rockets', 'hakeem-olajuwon', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-13', 'TT', 'Dirk Nowitzki', 'Dallas Mavericks', 'dirk-nowitzki', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-14', 'TT', 'Kevin Garnett', 'Minnesota Timberwolves', 'kevin-garnett', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-15', 'TT', 'Larry Bird', 'Boston Celtics', 'larry-bird', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-16', 'TT', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-17', 'TT', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-18', 'TT', 'Derik Queen', 'New Orleans Pelicans', 'derik-queen', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-19', 'TT', 'Carter Bryant', 'San Antonio Spurs', 'carter-bryant', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-2', 'TT', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-20', 'TT', 'Asa Newell', 'Atlanta Hawks', 'asa-newell', 'atlanta-hawks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-21', 'TT', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-22', 'TT', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers', 'yanic-konan-niederhauser', 'los-angeles-clippers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-23', 'TT', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-24', 'TT', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-25', 'TT', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'TT-3', 'TT', 'Joel Embiid', 'Philadelphia 76ers', 'joel-embiid', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-4', 'TT', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-5', 'TT', 'Anthony Davis', 'Dallas Mavericks', 'anthony-davis', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-6', 'TT', 'Kevin Durant', 'Phoenix Suns', 'kevin-durant', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-7', 'TT', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-8', 'TT', 'Kawhi Leonard', 'Los Angeles Clippers', 'kawhi-leonard', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'TT-9', 'TT', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-1', 'UV', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-10', 'UV', 'Nikola Jokić', 'Denver Nuggets', 'nikola-jokic', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-11', 'UV', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'UV-12', 'UV', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'UV-13', 'UV', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'UV-14', 'UV', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'UV-15', 'UV', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'UV-2', 'UV', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-3', 'UV', 'Kevin Durant', 'Houston Rockets', 'kevin-durant', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-4', 'UV', 'Jalen Brunson', 'New York Knicks', 'jalen-brunson', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-5', 'UV', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-6', 'UV', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-7', 'UV', 'Anthony Edwards', 'Minnesota Timberwolves', 'anthony-edwards', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-8', 'UV', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'UV-9', 'UV', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'VS-1', 'VS', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'VS-10', 'VS', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'VS-2', 'VS', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'VS-3', 'VS', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'VS-4', 'VS', 'Anthony Edwards', 'Minnesota Timberwolves', 'anthony-edwards', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'VS-5', 'VS', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'VS-6', 'VS', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'VS-7', 'VS', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'VS-8', 'VS', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'VS-9', 'VS', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'XW-1', 'XW', 'Donovan Mitchell', 'Cleveland Cavaliers', 'donovan-mitchell', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'XW-10', 'XW', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'XW-2', 'XW', 'Jalen Brunson', 'New York Knicks', 'jalen-brunson', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'XW-3', 'XW', 'Nikola Jokić', 'Denver Nuggets', 'nikola-jokic', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'XW-4', 'XW', 'Ja Morant', 'Memphis Grizzlies', 'ja-morant', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'XW-5', 'XW', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'XW-6', 'XW', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'XW-7', 'XW', 'LaMelo Ball', 'Charlotte Hornets', 'lamelo-ball', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-chrome', 'XW-8', 'XW', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'XW-9', 'XW', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-1', 'YQ', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-10', 'YQ', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-11', 'YQ', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-12', 'YQ', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-13', 'YQ', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-14', 'YQ', 'Asa Newell', 'Atlanta Hawks', 'asa-newell', 'atlanta-hawks', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-15', 'YQ', 'Carter Bryant', 'San Antonio Spurs', 'carter-bryant', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-2', 'YQ', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-3', 'YQ', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-4', 'YQ', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-5', 'YQ', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-6', 'YQ', 'Tre Johnson III', 'Washington Wizards', 'tre-johnson-iii', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-7', 'YQ', 'Jeremiah Fears', 'New Orleans Pelicans', 'jeremiah-fears', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-8', 'YQ', 'Danny Wolf', 'Brooklyn Nets', 'danny-wolf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-chrome', 'YQ-9', 'YQ', 'Collin Murray-Boyles', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', true, null, null)
on conflict (set_id, card_code) do update set
  subset = excluded.subset, player = excluded.player, team = excluded.team,
  player_id = excluded.player_id, team_id = excluded.team_id, season = excluded.season,
  rookie = excluded.rookie, variant = excluded.variant, jersey_number = excluded.jersey_number;

-- Associations carte/joueur (250)
insert into public.card_players (set_id, card_code, slot, player, player_id, team, team_id, season) values
  ('2025-26-topps-chrome', 'SY-13', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-chrome', 'SY-14', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'SY-15', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-chrome', 'SY-2', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'SY-3', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-chrome', 'SY-4', 1, 'Anthony Edwards', 'anthony-edwards', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'SY-5', 1, 'Paolo Banchero', 'paolo-banchero', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'SY-6', 1, 'Kyrie Irving', 'kyrie-irving', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'SY-7', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'SY-8', 1, 'LaMelo Ball', 'lamelo-ball', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'SY-9', 1, 'Magic Johnson', 'magic-johnson', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-AB', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-AN', 1, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-BS', 1, 'Ben Saraf', 'ben-saraf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-CC', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-CF', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-CMB', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-DH', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-DP', 1, 'Drake Powell', 'drake-powell', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-DQ', 1, 'Derik Queen', 'derik-queen', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-DW', 1, 'Danny Wolf', 'danny-wolf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-ED', 1, 'Egor Dëmin', 'egor-demin', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-JB', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-JR', 1, 'Jase Richardson', 'jase-richardson', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-KJ', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-KK', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-KM', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-KS', 1, 'Kobe Sanders', 'kobe-sanders', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-LMC', 1, 'Liam McNeeley', 'liam-mcneeley', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-NC', 1, 'Nique Clifford', 'nique-clifford', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-NE', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-NP', 1, 'Noah Penda', 'noah-penda', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-NT', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-RF', 1, 'Rasheer Fleming', 'rasheer-fleming', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-TP', 1, 'Tyrese Proctor', 'tyrese-proctor', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-TS', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-WCJ', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-WIR', 1, 'Will Richard', 'will-richard', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-WR', 1, 'Will Riley', 'will-riley', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-YH', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-chrome', 'TAIR-YKN', 1, 'Yanic Konan-Niederhäuser', 'yanic-konan-niederhauser', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-AB', 1, 'Anthony Black', 'anthony-black', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-AC', 1, 'Alex Caruso', 'alex-caruso', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-AG', 1, 'Aaron Gordon', 'aaron-gordon', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-AJJ', 1, 'AJ Johnson', 'aj-johnson', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-BSC', 1, 'Baylor Scheierman', 'baylor-scheierman', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-CA', 1, 'Cole Anthony', 'cole-anthony', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-CC', 1, 'Clint Capela', 'clint-capela', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-CJM', 1, 'CJ McCollum', 'cj-mccollum', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-CL', 1, 'Christian Laettner', 'christian-laettner', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-CW', 1, 'Cam Whitmore', 'cam-whitmore', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-DH', 1, 'Dwight Howard', 'dwight-howard', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-DJM', 1, 'Dejounte Murray', 'dejounte-murray', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-DL', 1, 'Dereck Lively II', 'dereck-lively-ii', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-DM', 1, 'Davion Mitchell', 'davion-mitchell', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-DT', 1, 'David Thompson', 'david-thompson', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-DW', 1, 'Derrick White', 'derrick-white', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-FVV', 1, 'Fred VanVleet', 'fred-vanvleet', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-GD', 1, 'Gradey Dick', 'gradey-dick', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-JC', 1, 'Jaylen Clark', 'jaylen-clark', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-JF', 1, 'Johnny Furphy', 'johnny-furphy', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-JH', 1, 'Jordan Hawkins', 'jordan-hawkins', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-JS', 1, 'Jamal Shead', 'jamal-shead', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-JSO', 1, 'Jeremy Sochan', 'jeremy-sochan', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-JT', 1, 'Jaylon Tyson', 'jaylon-tyson', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-JTM', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-KK', 1, 'Kyle Kuzma', 'kyle-kuzma', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-KYG', 1, 'Kyshawn George', 'kyshawn-george', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-OBI', 1, 'Obi Toppin', 'obi-toppin', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-PG', 1, 'Pau Gasol', 'pau-gasol', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-PPR', 1, 'Payton Pritchard', 'payton-pritchard', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-PS', 1, 'Peja Stojaković', 'peja-stojakovic', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-RD', 1, 'Ryan Dunn', 'ryan-dunn', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-RHA', 1, 'Rui Hachimura', 'rui-hachimura', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-SC', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-SH', 1, 'Scoot Henderson', 'scoot-henderson', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-TSJ', 1, 'Terrence Shannon Jr.', 'terrence-shannon-jr', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-WK', 1, 'Walker Kessler', 'walker-kessler', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'TAU-ZL', 1, 'Zach LaVine', 'zach-lavine', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-AB', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-AN', 1, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-BS', 1, 'Ben Saraf', 'ben-saraf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-CC', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-CMB', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-DH', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-DP', 1, 'Drake Powell', 'drake-powell', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-DQ', 1, 'Derik Queen', 'derik-queen', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-DW', 1, 'Danny Wolf', 'danny-wolf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-ED', 1, 'Egor Dëmin', 'egor-demin', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-JB', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-JR', 1, 'Jase Richardson', 'jase-richardson', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-KJ', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-KK', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-KM', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-LMC', 1, 'Liam McNeeley', 'liam-mcneeley', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-NC', 1, 'Nique Clifford', 'nique-clifford', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-NE', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-NT', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-TP', 1, 'Tyrese Proctor', 'tyrese-proctor', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-TS', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-WCJ', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-WIR', 1, 'Will Richard', 'will-richard', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-WR', 1, 'Will Riley', 'will-riley', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-chrome', 'TAUR2-YH', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-AI', 1, 'Allen Iverson', 'allen-iverson', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-AS', 1, 'Alex Sarr', 'alex-sarr', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-CH', 1, 'Chet Holmgren', 'chet-holmgren', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-DM', 1, 'Donovan Mitchell', 'donovan-mitchell', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-DN', 1, 'Dirk Nowitzki', 'dirk-nowitzki', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-DW', 1, 'Dwyane Wade', 'dwyane-wade', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-JB', 1, 'Jalen Brunson', 'jalen-brunson', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-JG', 1, 'Jalen Green', 'jalen-green', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-JH', 1, 'James Harden', 'james-harden', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-JM', 1, 'Jamal Murray', 'jamal-murray', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-JT', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-KD', 1, 'Kevin Durant', 'kevin-durant', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-KG', 1, 'Kevin Garnett', 'kevin-garnett', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-LB', 1, 'Larry Bird', 'larry-bird', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-LBJ', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-MJ', 1, 'Magic Johnson', 'magic-johnson', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-PB', 1, 'Paolo Banchero', 'paolo-banchero', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-SC', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-SGA', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-SO', 1, 'Shaquille O''Neal', 'shaquille-o-neal', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-TH', 1, 'Tyrese Haliburton', 'tyrese-haliburton', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-TM', 1, 'Tracy McGrady', 'tracy-mcgrady', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-VC', 1, 'Vince Carter', 'vince-carter', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-chrome', 'TCA-VW', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'TCA2-NJ', 1, 'Nikola Jokić', 'nikola-jokic', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-AB', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-AM', 1, 'Alijah Martin', 'alijah-martin', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-AN', 1, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-AT', 1, 'Adou Thiero', 'adou-thiero', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-BS', 1, 'Ben Saraf', 'ben-saraf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-CC', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-CF', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-CL', 1, 'Chaz Lanier', 'chaz-lanier', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-CMB', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-DH', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-DP', 1, 'Drake Powell', 'drake-powell', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-DQ', 1, 'Derik Queen', 'derik-queen', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-DW', 1, 'Danny Wolf', 'danny-wolf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-ED', 1, 'Egor Dëmin', 'egor-demin', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-JB', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-JBE', 1, 'Johni Broome', 'johni-broome', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-JR', 1, 'Jase Richardson', 'jase-richardson', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-KAJ', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-KB', 1, 'Koby Brea', 'koby-brea', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-KJ', 1, 'Kam Jones', 'kam-jones', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-KK', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-KM', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-KS', 1, 'Kobe Sanders', 'kobe-sanders', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-LM', 1, 'Liam McNeeley', 'liam-mcneeley', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-MP', 1, 'Micah Peavy', 'micah-peavy', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-MR', 1, 'Maxime Raynaud', 'maxime-raynaud', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-NC', 1, 'Nique Clifford', 'nique-clifford', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-NE', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-NP', 1, 'Noah Penda', 'noah-penda', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-NT', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-RF', 1, 'Rasheer Fleming', 'rasheer-fleming', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-RK', 1, 'Ryan Kalkbrenner', 'ryan-kalkbrenner', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-SJ', 1, 'Sion James', 'sion-james', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-TP', 1, 'Tyrese Proctor', 'tyrese-proctor', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-TS', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-WCJ', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-WIR', 1, 'Will Richard', 'will-richard', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-WR', 1, 'Will Riley', 'will-riley', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-YH', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-chrome', 'TCAR-YKN', 1, 'Yanic Konan-Niederhäuser', 'yanic-konan-niederhauser', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-chrome', 'TCGL-1', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'TCGL-2', 1, 'Stephon Castle', 'stephon-castle', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'TCGL-3', 1, 'Evan Mobley', 'evan-mobley', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-chrome', 'TCGR-1', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'TCGR-2', 1, 'Stephon Castle', 'stephon-castle', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'TCGR-3', 1, 'Evan Mobley', 'evan-mobley', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-chrome', 'TT-1', 1, 'Nikola Jokić', 'nikola-jokic', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-chrome', 'TT-10', 1, 'Karl-Anthony Towns', 'karl-anthony-towns', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-chrome', 'TT-11', 1, 'Shaquille O''Neal', 'shaquille-o-neal', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'TT-12', 1, 'Hakeem Olajuwon', 'hakeem-olajuwon', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-chrome', 'TT-13', 1, 'Dirk Nowitzki', 'dirk-nowitzki', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'TT-14', 1, 'Kevin Garnett', 'kevin-garnett', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'TT-15', 1, 'Larry Bird', 'larry-bird', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'TT-16', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'TT-17', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'TT-18', 1, 'Derik Queen', 'derik-queen', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-chrome', 'TT-19', 1, 'Carter Bryant', 'carter-bryant', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'TT-2', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-chrome', 'TT-20', 1, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-chrome', 'TT-21', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-chrome', 'TT-22', 1, 'Yanic Konan-Niederhäuser', 'yanic-konan-niederhauser', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-chrome', 'TT-23', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'TT-24', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-chrome', 'TT-25', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'TT-3', 1, 'Joel Embiid', 'joel-embiid', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-chrome', 'TT-4', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'TT-5', 1, 'Anthony Davis', 'anthony-davis', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'TT-6', 1, 'Kevin Durant', 'kevin-durant', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'TT-7', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'TT-8', 1, 'Kawhi Leonard', 'kawhi-leonard', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-chrome', 'TT-9', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'UV-1', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-chrome', 'UV-10', 1, 'Nikola Jokić', 'nikola-jokic', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-chrome', 'UV-11', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'UV-12', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'UV-13', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-chrome', 'UV-14', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'UV-15', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'UV-2', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-chrome', 'UV-3', 1, 'Kevin Durant', 'kevin-durant', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-chrome', 'UV-4', 1, 'Jalen Brunson', 'jalen-brunson', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-chrome', 'UV-5', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-chrome', 'UV-6', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'UV-7', 1, 'Anthony Edwards', 'anthony-edwards', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'UV-8', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'UV-9', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'VS-1', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'VS-10', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'VS-2', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-chrome', 'VS-3', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-chrome', 'VS-4', 1, 'Anthony Edwards', 'anthony-edwards', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-chrome', 'VS-5', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-chrome', 'VS-6', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'VS-7', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'VS-8', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-chrome', 'VS-9', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'XW-1', 1, 'Donovan Mitchell', 'donovan-mitchell', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-chrome', 'XW-10', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'XW-2', 1, 'Jalen Brunson', 'jalen-brunson', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-chrome', 'XW-3', 1, 'Nikola Jokić', 'nikola-jokic', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-chrome', 'XW-4', 1, 'Ja Morant', 'ja-morant', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-chrome', 'XW-5', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-chrome', 'XW-6', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-chrome', 'XW-7', 1, 'LaMelo Ball', 'lamelo-ball', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'XW-8', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'XW-9', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-1', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-10', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-11', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-12', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-13', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-14', 1, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-15', 1, 'Carter Bryant', 'carter-bryant', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-2', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-3', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-4', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-5', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-6', 1, 'Tre Johnson III', 'tre-johnson-iii', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-7', 1, 'Jeremiah Fears', 'jeremiah-fears', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-8', 1, 'Danny Wolf', 'danny-wolf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-chrome', 'YQ-9', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26')
on conflict (set_id, card_code, slot) do update set
  player = excluded.player, player_id = excluded.player_id, team = excluded.team,
  team_id = excluded.team_id, season = excluded.season;

commit;
