-- =====================================================================
-- Hoops Archive -- migration 0003g2 : cartes 2025-26-topps-finest (partie 2/2)
-- FICHIER GENERE AUTOMATIQUEMENT -- ne pas editer a la main.
-- Relancable sans risque (ON CONFLICT DO UPDATE).
-- =====================================================================

begin;

-- Cartes (264)
insert into public.cards (set_id, card_code, subset, player, team, player_id, team_id, season, rookie, variant, jersey_number) values
  ('2025-26-topps-finest', 'F-11', 'F', 'Cedric Coward', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-12', 'F', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-13', 'F', 'Derik Queen', 'New Orleans Pelicans', 'derik-queen', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-14', 'F', 'Carter Bryant', 'San Antonio Spurs', 'carter-bryant', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-15', 'F', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-16', 'F', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-17', 'F', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-18', 'F', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-19', 'F', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-2', 'F', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-20', 'F', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-21', 'F', 'Rasheer Fleming', 'Phoenix Suns', 'rasheer-fleming', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-22', 'F', 'Noah Penda', 'Orlando Magic', 'noah-penda', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-23', 'F', 'Sion James', 'Charlotte Hornets', 'sion-james', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-24', 'F', 'Ryan Kalkbrenner', 'Charlotte Hornets', 'ryan-kalkbrenner', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-25', 'F', 'Johni Broome', 'Philadelphia 76ers', 'johni-broome', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-26', 'F', 'Adou Thiero', 'Los Angeles Lakers', 'adou-thiero', 'los-angeles-lakers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-27', 'F', 'Chaz Lanier', 'Detroit Pistons', 'chaz-lanier', 'detroit-pistons', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-28', 'F', 'Kam Jones', 'Indiana Pacers', 'kam-jones', 'indiana-pacers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-29', 'F', 'Alijah Martin', 'Toronto Raptors', 'alijah-martin', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-3', 'F', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-30', 'F', 'Micah Peavy', 'New Orleans Pelicans', 'micah-peavy', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-4', 'F', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-5', 'F', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-6', 'F', 'Tre Johnson III', 'Washington Wizards', 'tre-johnson-iii', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-7', 'F', 'Jeremiah Fears', 'New Orleans Pelicans', 'jeremiah-fears', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-8', 'F', 'Egor Dëmin', 'Brooklyn Nets', 'egor-demin', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'F-9', 'F', 'Collin Murray-Boyles', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'FAU-AB', 'FAU', 'Anthony Black', 'Orlando Magic', 'anthony-black', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-AG', 'FAU', 'Aaron Gordon', 'Denver Nuggets', 'aaron-gordon', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-AH', 'FAU', 'Al Horford', 'Boston Celtics', 'al-horford', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-AR', 'FAU', 'Alex Sarr', 'Washington Wizards', 'alex-sarr', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-AS', 'FAU', 'Baylor Scheierman', 'Boston Celtics', 'baylor-scheierman', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-BJ', 'FAU', 'Bronny James Jr.', 'Los Angeles Lakers', 'bronny-james-jr', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-BM', 'FAU', 'Brandon Miller', 'Charlotte Hornets', 'brandon-miller', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-CA', 'FAU', 'Cody Williams', 'Utah Jazz', 'cody-williams', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-CC', 'FAU', 'Clint Capela', 'Atlanta Hawks', 'clint-capela', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-CJ', 'FAU', 'Cameron Johnson', 'Brooklyn Nets', 'cameron-johnson', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-CK', 'FAU', 'Corey Kispert', 'Washington Wizards', 'corey-kispert', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-CR', 'FAU', 'Cam Christie', 'Los Angeles Clippers', 'cam-christie', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-CS', 'FAU', 'Cam Spencer', 'Memphis Grizzlies', 'cam-spencer', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-CW', 'FAU', 'Cam Whitmore', 'Houston Rockets', 'cam-whitmore', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-DC', 'FAU', 'Devin Carter', 'Sacramento Kings', 'devin-carter', 'sacramento-kings', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-DD', 'FAU', 'Donte DiVincenzo', 'Minnesota Timberwolves', 'donte-divincenzo', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-DG', 'FAU', 'Daniel Gafford', 'Dallas Mavericks', 'daniel-gafford', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-DH', 'FAU', 'DaRon Holmes II', 'Denver Nuggets', 'daron-holmes-ii', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-DO', 'FAU', 'Dillon Jones', 'Oklahoma City Thunder', 'dillon-jones', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-DR', 'FAU', 'Duncan Robinson', 'Miami Heat', 'duncan-robinson', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-GD', 'FAU', 'Gradey Dick', 'Toronto Raptors', 'gradey-dick', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-GN', 'FAU', 'Georges Niang', 'Atlanta Hawks', 'georges-niang', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-GV', 'FAU', 'Gabe Vincent', 'Los Angeles Lakers', 'gabe-vincent', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-IH', 'FAU', 'Isaiah Hartenstein', 'Oklahoma City Thunder', 'isaiah-hartenstein', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JF', 'FAU', 'Johnny Furphy', 'Indiana Pacers', 'johnny-furphy', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JH', 'FAU', 'Jordan Hawkins', 'New Orleans Pelicans', 'jordan-hawkins', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JHS', 'FAU', 'Jalen Hood-Schifino', 'Philadelphia 76ers', 'jalen-hood-schifino', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JJ', 'FAU', 'Jaime Jaquez Jr.', 'Miami Heat', 'jaime-jaquez-jr', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JL', 'FAU', 'Jalen Williams', 'Oklahoma City Thunder', 'jalen-williams', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JO', 'FAU', 'Jrue Holiday', 'Boston Celtics', 'jrue-holiday', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JP', 'FAU', 'Jordan Poole', 'Washington Wizards', 'jordan-poole', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JT', 'FAU', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JU', 'FAU', 'Jamal Murray', 'Denver Nuggets', 'jamal-murray', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JW', 'FAU', 'Jaylen Wells', 'Memphis Grizzlies', 'jaylen-wells', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-JY', 'FAU', 'Jaylon Tyson', 'Cleveland Cavaliers', 'jaylon-tyson', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-KG', 'FAU', 'Kyshawn George', 'Washington Wizards', 'kyshawn-george', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-KM', 'FAU', 'Kris Murray', 'Portland Trail Blazers', 'kris-murray', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-KP', 'FAU', 'Kyle Filipowski', 'Utah Jazz', 'kyle-filipowski', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-KW', 'FAU', 'Kel''el Ware', 'Miami Heat', 'kelel-ware', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-MM', 'FAU', 'Miles McBride', 'New York Knicks', 'miles-mcbride', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-MS', 'FAU', 'Marcus Smart', 'Washington Wizards', 'marcus-smart', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-NT', 'FAU', 'Nikola Topić', 'Oklahoma City Thunder', 'nikola-topic', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-OI', 'FAU', 'Oso Ighodaro', 'Phoenix Suns', 'oso-ighodaro', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-PP', 'FAU', 'Payton Pritchard', 'Boston Celtics', 'payton-pritchard', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-QP', 'FAU', 'Quinten Post', 'Golden State Warriors', 'quinten-post', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-RD', 'FAU', 'Ryan Dunn', 'Phoenix Suns', 'ryan-dunn', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-RH', 'FAU', 'Ron Holland II', 'Detroit Pistons', 'ron-holland-ii', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-TD', 'FAU', 'Tristan da Silva', 'Orlando Magic', 'tristan-da-silva', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-TH', 'FAU', 'Tyler Herro', 'Miami Heat', 'tyler-herro', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-TK', 'FAU', 'Tyler Kolek', 'New York Knicks', 'tyler-kolek', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-TM', 'FAU', 'T.J. McConnell', 'Indiana Pacers', 'tj-mcconnell', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-TS', 'FAU', 'Terrence Shannon Jr.', 'Minnesota Timberwolves', 'terrence-shannon-jr', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-ZE', 'FAU', 'Zach Edey', 'Memphis Grizzlies', 'zach-edey', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FAU-ZR', 'FAU', 'Zaccharie Risacher', 'Atlanta Hawks', 'zaccharie-risacher', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FI-1', 'FI', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FI-10', 'FI', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'FI-2', 'FI', 'Anthony Edwards', 'Minnesota Timberwolves', 'anthony-edwards', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FI-3', 'FI', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FI-4', 'FI', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FI-5', 'FI', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FI-6', 'FI', 'Jalen Brunson', 'New York Knicks', 'jalen-brunson', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FI-7', 'FI', 'Donovan Mitchell', 'Cleveland Cavaliers', 'donovan-mitchell', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'FI-8', 'FI', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'FI-9', 'FI', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'H-1', 'H', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'H-10', 'H', 'Tyrese Haliburton', 'Indiana Pacers', 'tyrese-haliburton', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'H-11', 'H', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'H-12', 'H', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'H-13', 'H', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'H-14', 'H', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'H-15', 'H', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'H-2', 'H', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'H-3', 'H', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'H-4', 'H', 'Luka Dončić', 'Los Angeles Lakers', 'luka-doncic', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'H-5', 'H', 'Nikola Jokić', 'Denver Nuggets', 'nikola-jokic', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'H-6', 'H', 'Anthony Edwards', 'Minnesota Timberwolves', 'anthony-edwards', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'H-7', 'H', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'H-8', 'H', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'H-9', 'H', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-1', 'M', 'Allen Iverson', 'Philadelphia 76ers', 'allen-iverson', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-10', 'M', 'John Stockton', 'Utah Jazz', 'john-stockton', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-11', 'M', 'Ray Allen', 'Oklahoma City Thunder', 'ray-allen', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-12', 'M', 'Dwight Howard', 'Orlando Magic', 'dwight-howard', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-13', 'M', 'Grant Hill', 'Detroit Pistons', 'grant-hill', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-14', 'M', 'Paul Pierce', 'Boston Celtics', 'paul-pierce', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-15', 'M', 'Pau Gasol', 'Los Angeles Lakers', 'pau-gasol', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-16', 'M', 'Jason Kidd', 'Brooklyn Nets', 'jason-kidd', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-17', 'M', 'Hakeem Olajuwon', 'Houston Rockets', 'hakeem-olajuwon', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-18', 'M', 'Dennis Rodman', 'Chicago Bulls', 'dennis-rodman', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-19', 'M', 'David Robinson', 'San Antonio Spurs', 'david-robinson', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-2', 'M', 'Larry Bird', 'Boston Celtics', 'larry-bird', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-20', 'M', 'Vince Carter', 'Toronto Raptors', 'vince-carter', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-21', 'M', 'Dominique Wilkins', 'Atlanta Hawks', 'dominique-wilkins', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-22', 'M', 'Clyde Drexler', 'Portland Trail Blazers', 'clyde-drexler', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-23', 'M', 'Rip Hamilton', 'Detroit Pistons', 'rip-hamilton', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-24', 'M', 'Deron Williams', 'Utah Jazz', 'deron-williams', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-25', 'M', 'Robert Horry', 'Los Angeles Lakers', 'robert-horry', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-26', 'M', 'Peja Stojakovic', 'Sacramento Kings', 'peja-stojakovic', 'sacramento-kings', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-27', 'M', 'Chris Bosh', 'Miami Heat', 'chris-bosh', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-28', 'M', 'Joe Johnson', 'Atlanta Hawks', 'joe-johnson', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-29', 'M', 'Elton Brand', 'Los Angeles Clippers', 'elton-brand', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-3', 'M', 'Magic Johnson', 'Los Angeles Lakers', 'magic-johnson', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-30', 'M', 'Brandon Roy', 'Portland Trail Blazers', 'brandon-roy', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-4', 'M', 'Shaquille O''Neal', 'Los Angeles Lakers', 'shaquille-oneal', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-5', 'M', 'Dirk Nowitzki', 'Dallas Mavericks', 'dirk-nowitzki', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-6', 'M', 'Kevin Garnett', 'Boston Celtics', 'kevin-garnett', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-7', 'M', 'Carmelo Anthony', 'New York Knicks', 'carmelo-anthony', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-8', 'M', 'Dwyane Wade', 'Miami Heat', 'dwyane-wade', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'M-9', 'M', 'Tracy McGrady', 'Orlando Magic', 'tracy-mcgrady', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-AB', 'MA', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'MA-AI', 'MA', 'Allen Iverson', 'Philadelphia 76ers', 'allen-iverson', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-CC', 'MA', 'Cedric Coward', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'MA-CF', 'MA', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'MA-CMB', 'MA', 'Collin Murray-Boyles', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-DF', 'MA', 'De''Aaron Fox', 'San Antonio Spurs', 'deaaron-fox', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-DH', 'MA', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'MA-DN', 'MA', 'Dirk Nowitzki', 'Dallas Mavericks', 'dirk-nowitzki', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-DO', 'MA', 'Dwight Howard', 'Orlando Magic', 'dwight-howard', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-DQ', 'MA', 'Derik Queen', 'New Orleans Pelicans', 'derik-queen', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'MA-DR', 'MA', 'Dennis Rodman', 'Chicago Bulls', 'dennis-rodman', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-DW', 'MA', 'Dwyane Wade', 'Miami Heat', 'dwyane-wade', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-ED', 'MA', 'Egor Dëmin', 'Brooklyn Nets', 'egor-demin', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'MA-GA', 'MA', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-JB', 'MA', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'MA-JR', 'MA', 'Jalen Brunson', 'New York Knicks', 'jalen-brunson', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-KAJ', 'MA', 'Kareem Abdul-Jabbar', 'Los Angeles Lakers', 'kareem-abdul-jabbar', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-KD', 'MA', 'Kevin Durant', 'Phoenix Suns', 'kevin-durant', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-KJ', 'MA', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'MA-KK', 'MA', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-KL', 'MA', 'Karl Malone', 'Utah Jazz', 'karl-malone', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-KM', 'MA', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-LB', 'MA', 'Larry Bird', 'Boston Celtics', 'larry-bird', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-LBJ', 'MA', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-NE', 'MA', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-NT', 'MA', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-PB', 'MA', 'Paolo Banchero', 'Orlando Magic', 'paolo-banchero', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-PG', 'MA', 'Pau Gasol', 'Los Angeles Lakers', 'pau-gasol', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-PP', 'MA', 'Paul Pierce', 'Boston Celtics', 'paul-pierce', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-PS', 'MA', 'Peja Stojakovic', 'Sacramento Kings', 'peja-stojakovic', 'sacramento-kings', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-RA', 'MA', 'Ray Allen', 'Boston Celtics', 'ray-allen', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-RH', 'MA', 'Rip Hamilton', 'Detroit Pistons', 'rip-hamilton', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-RW', 'MA', 'Rasheed Wallace', 'Portland Trail Blazers', 'rasheed-wallace', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-SC', 'MA', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-SGA', 'MA', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-SK', 'MA', 'Shawn Kemp', 'Cleveland Cavaliers', 'shawn-kemp', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-SO', 'MA', 'Shaquille O''Neal', 'Los Angeles Lakers', 'shaquille-oneal', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-TE', 'MA', 'Tyler Herro', 'Miami Heat', 'tyler-herro', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-TH', 'MA', 'Tyrese Haliburton', 'Indiana Pacers', 'tyrese-haliburton', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-TM', 'MA', 'Tracy McGrady', 'Toronto Raptors', 'tracy-mcgrady', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-TP', 'MA', 'Tony Parker', 'San Antonio Spurs', 'tony-parker', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-TS', 'MA', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-VC', 'MA', 'Vince Carter', 'Toronto Raptors', 'vince-carter', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-VW', 'MA', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-WC', 'MA', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-YH', 'MA', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'MA-ZR', 'MA', 'Zaccharie Risacher', 'Atlanta Hawks', 'zaccharie-risacher', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-1', 'P', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-10', 'P', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'P-11', 'P', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'P-12', 'P', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'P-13', 'P', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'P-14', 'P', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'P-15', 'P', 'Tre Johnson III', 'Washington Wizards', 'tre-johnson-iii', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'P-16', 'P', 'Shaquille O''Neal', 'Los Angeles Lakers', 'shaquille-oneal', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-17', 'P', 'Allen Iverson', 'Philadelphia 76ers', 'allen-iverson', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-18', 'P', 'Dirk Nowitzki', 'Dallas Mavericks', 'dirk-nowitzki', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-19', 'P', 'Vince Carter', 'Toronto Raptors', 'vince-carter', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-2', 'P', 'Anthony Edwards', 'Minnesota Timberwolves', 'anthony-edwards', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-20', 'P', 'Dwyane Wade', 'Miami Heat', 'dwyane-wade', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-3', 'P', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-4', 'P', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-5', 'P', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-6', 'P', 'Tyrese Haliburton', 'Indiana Pacers', 'tyrese-haliburton', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-7', 'P', 'Jalen Brunson', 'New York Knicks', 'jalen-brunson', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-8', 'P', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'P-9', 'P', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'RFA-AB', 'RFA', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-AM', 'RFA', 'Alijah Martin', 'Toronto Raptors', 'alijah-martin', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-AN', 'RFA', 'Asa Newell', 'Atlanta Hawks', 'asa-newell', 'atlanta-hawks', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-AT', 'RFA', 'Adou Thiero', 'Los Angeles Lakers', 'adou-thiero', 'los-angeles-lakers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-BB', 'RFA', 'Brooks Barnhizer', 'Oklahoma City Thunder', 'brooks-barnhizer', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-BS', 'RFA', 'Ben Saraf', 'Brooklyn Nets', 'ben-saraf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-CC', 'RFA', 'Cedric Coward', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-CF', 'RFA', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-CL', 'RFA', 'Chaz Lanier', 'Detroit Pistons', 'chaz-lanier', 'detroit-pistons', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-CMB', 'RFA', 'Collin Murray-Boyles', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-DH', 'RFA', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-DK', 'RFA', 'Derik Queen', 'New Orleans Pelicans', 'derik-queen', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-DP', 'RFA', 'Drake Powell', 'Brooklyn Nets', 'drake-powell', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-DW', 'RFA', 'Danny Wolf', 'Brooklyn Nets', 'danny-wolf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-ED', 'RFA', 'Egor Dëmin', 'Brooklyn Nets', 'egor-demin', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-JB', 'RFA', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-JO', 'RFA', 'Johni Broome', 'Philadelphia 76ers', 'johni-broome', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-JR', 'RFA', 'Jase Richardson', 'Orlando Magic', 'jase-richardson', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-JW', 'RFA', 'Jamir Watkins', 'Washington Wizards', 'jamir-watkins', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-KB', 'RFA', 'Koby Brea', 'Phoenix Suns', 'koby-brea', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-KJ', 'RFA', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-KK', 'RFA', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-KM', 'RFA', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-KO', 'RFA', 'Kam Jones', 'Indiana Pacers', 'kam-jones', 'indiana-pacers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-LM', 'RFA', 'Liam McNeeley', 'Charlotte Hornets', 'liam-mcneeley', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-MP', 'RFA', 'Micah Peavy', 'New Orleans Pelicans', 'micah-peavy', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-MR', 'RFA', 'Maxime Raynaud', 'Sacramento Kings', 'maxime-raynaud', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-NC', 'RFA', 'Nique Clifford', 'Sacramento Kings', 'nique-clifford', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-NE', 'RFA', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-NP', 'RFA', 'Noah Penda', 'Orlando Magic', 'noah-penda', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-NT', 'RFA', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-RF', 'RFA', 'Rasheer Fleming', 'Phoenix Suns', 'rasheer-fleming', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-RK', 'RFA', 'Ryan Kalkbrenner', 'Charlotte Hornets', 'ryan-kalkbrenner', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-SJ', 'RFA', 'Sion James', 'Charlotte Hornets', 'sion-james', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-TP', 'RFA', 'Tyrese Proctor', 'Cleveland Cavaliers', 'tyrese-proctor', 'cleveland-cavaliers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-TS', 'RFA', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-WC', 'RFA', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-WR', 'RFA', 'Will Riley', 'Washington Wizards', 'will-riley', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-YH', 'RFA', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'RFA-YK', 'RFA', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers', 'yanic-konan-niederhauser', 'los-angeles-clippers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'TM-1', 'TM', 'Cade Cunningham', 'Detroit Pistons', 'cade-cunningham', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-10', 'TM', 'Anthony Edwards', 'Minnesota Timberwolves', 'anthony-edwards', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-11', 'TM', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-12', 'TM', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-13', 'TM', 'Donovan Mitchell', 'Cleveland Cavaliers', 'donovan-mitchell', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-14', 'TM', 'Amen Thompson', 'Houston Rockets', 'amen-thompson', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-15', 'TM', 'LaMelo Ball', 'Charlotte Hornets', 'lamelo-ball', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-16', 'TM', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'TM-17', 'TM', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'TM-18', 'TM', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'TM-19', 'TM', 'Tre Johnson III', 'Washington Wizards', 'tre-johnson-iii', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'TM-2', 'TM', 'Devin Booker', 'Phoenix Suns', 'devin-booker', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-20', 'TM', 'Jeremiah Fears', 'New Orleans Pelicans', 'jeremiah-fears', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-finest', 'TM-3', 'TM', 'Paolo Banchero', 'Orlando Magic', 'paolo-banchero', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-4', 'TM', 'Ja Morant', 'Memphis Grizzlies', 'ja-morant', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-5', 'TM', 'Trae Young', 'Atlanta Hawks', 'trae-young', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-6', 'TM', 'Luka Dončić', 'Los Angeles Lakers', 'luka-doncic', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-7', 'TM', 'Nikola Jokić', 'Denver Nuggets', 'nikola-jokic', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-8', 'TM', 'Tyrese Haliburton', 'Indiana Pacers', 'tyrese-haliburton', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-finest', 'TM-9', 'TM', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null)
on conflict (set_id, card_code) do update set
  subset = excluded.subset, player = excluded.player, team = excluded.team,
  player_id = excluded.player_id, team_id = excluded.team_id, season = excluded.season,
  rookie = excluded.rookie, variant = excluded.variant, jersey_number = excluded.jersey_number;

-- Associations carte/joueur (264)
insert into public.card_players (set_id, card_code, slot, player, player_id, team, team_id, season) values
  ('2025-26-topps-finest', 'F-11', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-finest', 'F-12', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-finest', 'F-13', 1, 'Derik Queen', 'derik-queen', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-finest', 'F-14', 1, 'Carter Bryant', 'carter-bryant', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'F-15', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'F-16', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-finest', 'F-17', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-finest', 'F-18', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'F-19', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'F-2', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'F-20', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'F-21', 1, 'Rasheer Fleming', 'rasheer-fleming', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-finest', 'F-22', 1, 'Noah Penda', 'noah-penda', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'F-23', 1, 'Sion James', 'sion-james', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'F-24', 1, 'Ryan Kalkbrenner', 'ryan-kalkbrenner', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'F-25', 1, 'Johni Broome', 'johni-broome', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'F-26', 1, 'Adou Thiero', 'adou-thiero', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'F-27', 1, 'Chaz Lanier', 'chaz-lanier', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-finest', 'F-28', 1, 'Kam Jones', 'kam-jones', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-finest', 'F-29', 1, 'Alijah Martin', 'alijah-martin', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'F-3', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'F-30', 1, 'Micah Peavy', 'micah-peavy', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-finest', 'F-4', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'F-5', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'F-6', 1, 'Tre Johnson III', 'tre-johnson-iii', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'F-7', 1, 'Jeremiah Fears', 'jeremiah-fears', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-finest', 'F-8', 1, 'Egor Dëmin', 'egor-demin', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'F-9', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'FAU-AB', 1, 'Anthony Black', 'anthony-black', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'FAU-AG', 1, 'Aaron Gordon', 'aaron-gordon', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-finest', 'FAU-AH', 1, 'Al Horford', 'al-horford', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'FAU-AR', 1, 'Alex Sarr', 'alex-sarr', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'FAU-AS', 1, 'Baylor Scheierman', 'baylor-scheierman', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'FAU-BJ', 1, 'Bronny James Jr.', 'bronny-james-jr', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'FAU-BM', 1, 'Brandon Miller', 'brandon-miller', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'FAU-CA', 1, 'Cody Williams', 'cody-williams', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'FAU-CC', 1, 'Clint Capela', 'clint-capela', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-finest', 'FAU-CJ', 1, 'Cameron Johnson', 'cameron-johnson', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'FAU-CK', 1, 'Corey Kispert', 'corey-kispert', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'FAU-CR', 1, 'Cam Christie', 'cam-christie', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-finest', 'FAU-CS', 1, 'Cam Spencer', 'cam-spencer', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-finest', 'FAU-CW', 1, 'Cam Whitmore', 'cam-whitmore', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-finest', 'FAU-DC', 1, 'Devin Carter', 'devin-carter', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-finest', 'FAU-DD', 1, 'Donte DiVincenzo', 'donte-divincenzo', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-finest', 'FAU-DG', 1, 'Daniel Gafford', 'daniel-gafford', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'FAU-DH', 1, 'DaRon Holmes II', 'daron-holmes-ii', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-finest', 'FAU-DO', 1, 'Dillon Jones', 'dillon-jones', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'FAU-DR', 1, 'Duncan Robinson', 'duncan-robinson', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'FAU-GD', 1, 'Gradey Dick', 'gradey-dick', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'FAU-GN', 1, 'Georges Niang', 'georges-niang', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-finest', 'FAU-GV', 1, 'Gabe Vincent', 'gabe-vincent', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'FAU-IH', 1, 'Isaiah Hartenstein', 'isaiah-hartenstein', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JF', 1, 'Johnny Furphy', 'johnny-furphy', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JH', 1, 'Jordan Hawkins', 'jordan-hawkins', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JHS', 1, 'Jalen Hood-Schifino', 'jalen-hood-schifino', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JJ', 1, 'Jaime Jaquez Jr.', 'jaime-jaquez-jr', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JL', 1, 'Jalen Williams', 'jalen-williams', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JO', 1, 'Jrue Holiday', 'jrue-holiday', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JP', 1, 'Jordan Poole', 'jordan-poole', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JT', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JU', 1, 'Jamal Murray', 'jamal-murray', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JW', 1, 'Jaylen Wells', 'jaylen-wells', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-finest', 'FAU-JY', 1, 'Jaylon Tyson', 'jaylon-tyson', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-finest', 'FAU-KG', 1, 'Kyshawn George', 'kyshawn-george', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'FAU-KM', 1, 'Kris Murray', 'kris-murray', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-finest', 'FAU-KP', 1, 'Kyle Filipowski', 'kyle-filipowski', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'FAU-KW', 1, 'Kel''el Ware', 'kelel-ware', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'FAU-MM', 1, 'Miles McBride', 'miles-mcbride', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-finest', 'FAU-MS', 1, 'Marcus Smart', 'marcus-smart', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'FAU-NT', 1, 'Nikola Topić', 'nikola-topic', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'FAU-OI', 1, 'Oso Ighodaro', 'oso-ighodaro', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-finest', 'FAU-PP', 1, 'Payton Pritchard', 'payton-pritchard', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'FAU-QP', 1, 'Quinten Post', 'quinten-post', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-finest', 'FAU-RD', 1, 'Ryan Dunn', 'ryan-dunn', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-finest', 'FAU-RH', 1, 'Ron Holland II', 'ron-holland-ii', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-finest', 'FAU-TD', 1, 'Tristan da Silva', 'tristan-da-silva', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'FAU-TH', 1, 'Tyler Herro', 'tyler-herro', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'FAU-TK', 1, 'Tyler Kolek', 'tyler-kolek', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-finest', 'FAU-TM', 1, 'T.J. McConnell', 'tj-mcconnell', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-finest', 'FAU-TS', 1, 'Terrence Shannon Jr.', 'terrence-shannon-jr', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-finest', 'FAU-ZE', 1, 'Zach Edey', 'zach-edey', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-finest', 'FAU-ZR', 1, 'Zaccharie Risacher', 'zaccharie-risacher', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-finest', 'FI-1', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'FI-10', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'FI-2', 1, 'Anthony Edwards', 'anthony-edwards', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-finest', 'FI-3', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-finest', 'FI-4', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-finest', 'FI-5', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'FI-6', 1, 'Jalen Brunson', 'jalen-brunson', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-finest', 'FI-7', 1, 'Donovan Mitchell', 'donovan-mitchell', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-finest', 'FI-8', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'FI-9', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'H-1', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'H-10', 1, 'Tyrese Haliburton', 'tyrese-haliburton', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-finest', 'H-11', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'H-12', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'H-13', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'H-14', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'H-15', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'H-2', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'H-3', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-finest', 'H-4', 1, 'Luka Dončić', 'luka-doncic', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'H-5', 1, 'Nikola Jokić', 'nikola-jokic', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-finest', 'H-6', 1, 'Anthony Edwards', 'anthony-edwards', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-finest', 'H-7', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'H-8', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-finest', 'H-9', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'M-1', 1, 'Allen Iverson', 'allen-iverson', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'M-10', 1, 'John Stockton', 'john-stockton', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'M-11', 1, 'Ray Allen', 'ray-allen', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'M-12', 1, 'Dwight Howard', 'dwight-howard', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'M-13', 1, 'Grant Hill', 'grant-hill', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-finest', 'M-14', 1, 'Paul Pierce', 'paul-pierce', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'M-15', 1, 'Pau Gasol', 'pau-gasol', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'M-16', 1, 'Jason Kidd', 'jason-kidd', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'M-17', 1, 'Hakeem Olajuwon', 'hakeem-olajuwon', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-finest', 'M-18', 1, 'Dennis Rodman', 'dennis-rodman', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-finest', 'M-19', 1, 'David Robinson', 'david-robinson', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'M-2', 1, 'Larry Bird', 'larry-bird', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'M-20', 1, 'Vince Carter', 'vince-carter', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'M-21', 1, 'Dominique Wilkins', 'dominique-wilkins', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-finest', 'M-22', 1, 'Clyde Drexler', 'clyde-drexler', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-finest', 'M-23', 1, 'Rip Hamilton', 'rip-hamilton', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-finest', 'M-24', 1, 'Deron Williams', 'deron-williams', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'M-25', 1, 'Robert Horry', 'robert-horry', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'M-26', 1, 'Peja Stojakovic', 'peja-stojakovic', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-finest', 'M-27', 1, 'Chris Bosh', 'chris-bosh', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'M-28', 1, 'Joe Johnson', 'joe-johnson', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-finest', 'M-29', 1, 'Elton Brand', 'elton-brand', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-finest', 'M-3', 1, 'Magic Johnson', 'magic-johnson', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'M-30', 1, 'Brandon Roy', 'brandon-roy', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-finest', 'M-4', 1, 'Shaquille O''Neal', 'shaquille-oneal', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'M-5', 1, 'Dirk Nowitzki', 'dirk-nowitzki', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'M-6', 1, 'Kevin Garnett', 'kevin-garnett', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'M-7', 1, 'Carmelo Anthony', 'carmelo-anthony', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-finest', 'M-8', 1, 'Dwyane Wade', 'dwyane-wade', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'M-9', 1, 'Tracy McGrady', 'tracy-mcgrady', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'MA-AB', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'MA-AI', 1, 'Allen Iverson', 'allen-iverson', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'MA-CC', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-finest', 'MA-CF', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'MA-CMB', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'MA-DF', 1, 'De''Aaron Fox', 'deaaron-fox', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'MA-DH', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'MA-DN', 1, 'Dirk Nowitzki', 'dirk-nowitzki', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'MA-DO', 1, 'Dwight Howard', 'dwight-howard', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'MA-DQ', 1, 'Derik Queen', 'derik-queen', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-finest', 'MA-DR', 1, 'Dennis Rodman', 'dennis-rodman', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-finest', 'MA-DW', 1, 'Dwyane Wade', 'dwyane-wade', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'MA-ED', 1, 'Egor Dëmin', 'egor-demin', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'MA-GA', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-finest', 'MA-JB', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-finest', 'MA-JR', 1, 'Jalen Brunson', 'jalen-brunson', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-finest', 'MA-KAJ', 1, 'Kareem Abdul-Jabbar', 'kareem-abdul-jabbar', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'MA-KD', 1, 'Kevin Durant', 'kevin-durant', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-finest', 'MA-KJ', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'MA-KK', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'MA-KL', 1, 'Karl Malone', 'karl-malone', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'MA-KM', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-finest', 'MA-LB', 1, 'Larry Bird', 'larry-bird', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'MA-LBJ', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'MA-NE', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-finest', 'MA-NT', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'MA-PB', 1, 'Paolo Banchero', 'paolo-banchero', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'MA-PG', 1, 'Pau Gasol', 'pau-gasol', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'MA-PP', 1, 'Paul Pierce', 'paul-pierce', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'MA-PS', 1, 'Peja Stojakovic', 'peja-stojakovic', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-finest', 'MA-RA', 1, 'Ray Allen', 'ray-allen', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'MA-RH', 1, 'Rip Hamilton', 'rip-hamilton', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-finest', 'MA-RW', 1, 'Rasheed Wallace', 'rasheed-wallace', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-finest', 'MA-SC', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-finest', 'MA-SGA', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'MA-SK', 1, 'Shawn Kemp', 'shawn-kemp', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-finest', 'MA-SO', 1, 'Shaquille O''Neal', 'shaquille-oneal', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'MA-TE', 1, 'Tyler Herro', 'tyler-herro', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'MA-TH', 1, 'Tyrese Haliburton', 'tyrese-haliburton', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-finest', 'MA-TM', 1, 'Tracy McGrady', 'tracy-mcgrady', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'MA-TP', 1, 'Tony Parker', 'tony-parker', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'MA-TS', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'MA-VC', 1, 'Vince Carter', 'vince-carter', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'MA-VW', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'MA-WC', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'MA-YH', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-finest', 'MA-ZR', 1, 'Zaccharie Risacher', 'zaccharie-risacher', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-finest', 'P-1', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'P-10', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'P-11', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'P-12', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'P-13', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'P-14', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'P-15', 1, 'Tre Johnson III', 'tre-johnson-iii', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'P-16', 1, 'Shaquille O''Neal', 'shaquille-oneal', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'P-17', 1, 'Allen Iverson', 'allen-iverson', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'P-18', 1, 'Dirk Nowitzki', 'dirk-nowitzki', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'P-19', 1, 'Vince Carter', 'vince-carter', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'P-2', 1, 'Anthony Edwards', 'anthony-edwards', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-finest', 'P-20', 1, 'Dwyane Wade', 'dwyane-wade', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'P-3', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-finest', 'P-4', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-finest', 'P-5', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'P-6', 1, 'Tyrese Haliburton', 'tyrese-haliburton', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-finest', 'P-7', 1, 'Jalen Brunson', 'jalen-brunson', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-finest', 'P-8', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-finest', 'P-9', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'RFA-AB', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'RFA-AM', 1, 'Alijah Martin', 'alijah-martin', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'RFA-AN', 1, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-finest', 'RFA-AT', 1, 'Adou Thiero', 'adou-thiero', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'RFA-BB', 1, 'Brooks Barnhizer', 'brooks-barnhizer', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'RFA-BS', 1, 'Ben Saraf', 'ben-saraf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'RFA-CC', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-finest', 'RFA-CF', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'RFA-CL', 1, 'Chaz Lanier', 'chaz-lanier', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-finest', 'RFA-CMB', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-finest', 'RFA-DH', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'RFA-DK', 1, 'Derik Queen', 'derik-queen', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-finest', 'RFA-DP', 1, 'Drake Powell', 'drake-powell', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'RFA-DW', 1, 'Danny Wolf', 'danny-wolf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'RFA-ED', 1, 'Egor Dëmin', 'egor-demin', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'RFA-JB', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-finest', 'RFA-JO', 1, 'Johni Broome', 'johni-broome', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'RFA-JR', 1, 'Jase Richardson', 'jase-richardson', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'RFA-JW', 1, 'Jamir Watkins', 'jamir-watkins', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'RFA-KB', 1, 'Koby Brea', 'koby-brea', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-finest', 'RFA-KJ', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-finest', 'RFA-KK', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'RFA-KM', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-finest', 'RFA-KO', 1, 'Kam Jones', 'kam-jones', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-finest', 'RFA-LM', 1, 'Liam McNeeley', 'liam-mcneeley', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'RFA-MP', 1, 'Micah Peavy', 'micah-peavy', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-finest', 'RFA-MR', 1, 'Maxime Raynaud', 'maxime-raynaud', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-finest', 'RFA-NC', 1, 'Nique Clifford', 'nique-clifford', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-finest', 'RFA-NE', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-finest', 'RFA-NP', 1, 'Noah Penda', 'noah-penda', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'RFA-NT', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-finest', 'RFA-RF', 1, 'Rasheer Fleming', 'rasheer-fleming', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-finest', 'RFA-RK', 1, 'Ryan Kalkbrenner', 'ryan-kalkbrenner', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'RFA-SJ', 1, 'Sion James', 'sion-james', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'RFA-TP', 1, 'Tyrese Proctor', 'tyrese-proctor', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-finest', 'RFA-TS', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-finest', 'RFA-WC', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-finest', 'RFA-WR', 1, 'Will Riley', 'will-riley', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'RFA-YH', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-finest', 'RFA-YK', 1, 'Yanic Konan-Niederhäuser', 'yanic-konan-niederhauser', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-finest', 'TM-1', 1, 'Cade Cunningham', 'cade-cunningham', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-finest', 'TM-10', 1, 'Anthony Edwards', 'anthony-edwards', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-finest', 'TM-11', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'TM-12', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'TM-13', 1, 'Donovan Mitchell', 'donovan-mitchell', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-finest', 'TM-14', 1, 'Amen Thompson', 'amen-thompson', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-finest', 'TM-15', 1, 'LaMelo Ball', 'lamelo-ball', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-finest', 'TM-16', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-finest', 'TM-17', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-finest', 'TM-18', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-finest', 'TM-19', 1, 'Tre Johnson III', 'tre-johnson-iii', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-finest', 'TM-2', 1, 'Devin Booker', 'devin-booker', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-finest', 'TM-20', 1, 'Jeremiah Fears', 'jeremiah-fears', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-finest', 'TM-3', 1, 'Paolo Banchero', 'paolo-banchero', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-finest', 'TM-4', 1, 'Ja Morant', 'ja-morant', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-finest', 'TM-5', 1, 'Trae Young', 'trae-young', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-finest', 'TM-6', 1, 'Luka Dončić', 'luka-doncic', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-finest', 'TM-7', 1, 'Nikola Jokić', 'nikola-jokic', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-finest', 'TM-8', 1, 'Tyrese Haliburton', 'tyrese-haliburton', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-finest', 'TM-9', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26')
on conflict (set_id, card_code, slot) do update set
  player = excluded.player, player_id = excluded.player_id, team = excluded.team,
  team_id = excluded.team_id, season = excluded.season;

commit;
