-- =====================================================================
-- Hoops Archive -- migration 0003a : sets + sous-ensembles pour 7 nouveaux sets Topps 2025-26
-- FICHIER GENERE AUTOMATIQUEMENT -- ne pas editer a la main.
-- Relancable sans risque (ON CONFLICT DO UPDATE).
-- =====================================================================

begin;

-- 1. Les sets
insert into public.sets (id, name, manufacturer, release_date, base_count) values
  ('2025-26-topps-basketball', '2025-26 Topps Basketball', 'Topps', '2025-10-23', 270),
  ('2025-26-topps-holiday', '2025-26 Topps Holiday', 'Topps', '2025-10-30', 200),
  ('2025-26-topps-chrome', '2025-26 Topps Chrome', 'Topps', '2025-12-18', 299),
  ('2025-26-topps-chrome-sapphire', '2025-26 Topps Chrome Sapphire', 'Topps', null, 300),
  ('2025-26-topps-midnight', '2025-26 Topps Midnight', 'Topps', null, 100),
  ('2025-26-topps-finest', '2025-26 Topps Finest', 'Topps', '2026-02-26', 300),
  ('2025-26-topps-three', '2025-26 Topps Three', 'Topps', '2026-03-05', 100)
on conflict (id) do update set
  name = excluded.name, manufacturer = excluded.manufacturer,
  release_date = excluded.release_date, base_count = excluded.base_count;

-- 2. Les sous-ensembles (191)
insert into public.subsets (set_id, id, name, type) values
  ('2025-26-topps-basketball', 'combo', 'Combo Cards', 'base'),
  ('2025-26-topps-basketball', 'base', 'Base Cards', 'base'),
  ('2025-26-topps-basketball', 'NA', 'New Applicants Autograph', 'autograph'),
  ('2025-26-topps-basketball', 'TNS', 'Topps Notch Signatures', 'autograph'),
  ('2025-26-topps-basketball', 'ME', 'Marks Of Excellence', 'insert'),
  ('2025-26-topps-basketball', 'CM', 'Contemporary Marks', 'insert'),
  ('2025-26-topps-basketball', '80B2', '1980-81 Topps Basketball Autograph', 'autograph'),
  ('2025-26-topps-basketball', 'TFRA', 'Flagship Real One Autograph', 'autograph'),
  ('2025-26-topps-basketball', '80B2R', '1980-81 Topps Basketball Rookie Autograph', 'autograph'),
  ('2025-26-topps-basketball', 'TFRR', 'Flagship Real One Rookie Autograph', 'autograph'),
  ('2025-26-topps-basketball', 'SSA', 'Shopping Spree Signatures', 'autograph'),
  ('2025-26-topps-basketball', 'BSI', 'Signed And Sealed', 'insert'),
  ('2025-26-topps-basketball', 'HM', 'Havoc Marks', 'insert'),
  ('2025-26-topps-basketball', 'RS', 'Retail Rush Signatures', 'autograph'),
  ('2025-26-topps-basketball', 'RP', 'Rookie Photo Shoot Autograph', 'autograph'),
  ('2025-26-topps-basketball', '80BT', '1980-81 Topps Basketball Triple Autograph', 'autograph'),
  ('2025-26-topps-basketball', 'RPD', 'Rookie Photo Shoot Dual Autograph', 'autograph'),
  ('2025-26-topps-basketball', 'TFRA2', 'Flagship Real One Autograph Spike Lee', 'autograph'),
  ('2025-26-topps-basketball', '80CA2', '1980-81 Topps Chrome Basketball Veteran Autograph', 'autograph'),
  ('2025-26-topps-basketball', '80CR2', '1980-81 Topps Chrome Basketball Rookie Autograph', 'autograph'),
  ('2025-26-topps-basketball', '80BK', '1980-81 Topps Basketball', 'insert'),
  ('2025-26-topps-basketball', '8B', '8 Bit Ballers', 'insert'),
  ('2025-26-topps-basketball', 'NL', 'No Limit', 'insert'),
  ('2025-26-topps-basketball', 'LST', 'Limited Stock Legends', 'insert'),
  ('2025-26-topps-basketball', 'SA', 'Stars Of The NBA', 'insert'),
  ('2025-26-topps-basketball', 'GN', 'Generation Now', 'insert'),
  ('2025-26-topps-basketball', 'SS', 'Scan And Slam', 'insert'),
  ('2025-26-topps-basketball', 'DD', 'The Daily Dribble', 'insert'),
  ('2025-26-topps-basketball', 'NS', 'New School', 'insert'),
  ('2025-26-topps-basketball', 'TC', '1980-81 Topps Chrome Basketball', 'insert'),
  ('2025-26-topps-basketball', 'RTS', 'Rise To Stardom', 'insert'),
  ('2025-26-topps-basketball', 'PP', 'Power Players', 'insert'),
  ('2025-26-topps-basketball', 'L', 'Levitation', 'insert'),
  ('2025-26-topps-basketball', 'CC', 'Clutch City Prospects', 'insert'),
  ('2025-26-topps-basketball', 'MVP', 'MVP Vault', 'insert'),
  ('2025-26-topps-basketball', 'FR', 'Fanatics Authentic Redemption', 'insert'),
  ('2025-26-topps-basketball', 'C25', 'Class Of ''25', 'insert'),
  ('2025-26-topps-basketball', 'BB', 'Big Box Ballers', 'insert'),
  ('2025-26-topps-basketball', 'CC2', 'Companion Topps Cards', 'insert'),
  ('2025-26-topps-basketball', 'OTC', 'Oversized Topps Cards', 'insert'),
  ('2025-26-topps-basketball', 'CCV', 'Companion Topps Cards Short Prints', 'insert'),
  ('2025-26-topps-basketball', 'OTSP', 'Oversized Topps Cards Short Prints', 'insert'),
  ('2025-26-topps-basketball', 'AK', 'All Kings', 'insert'),
  ('2025-26-topps-basketball', 'HS', 'Hardwood Stars', 'insert'),
  ('2025-26-topps-basketball', 'CC3', 'Comic Court', 'insert'),
  ('2025-26-topps-basketball', 'SB', 'Sonic Boom', 'insert'),
  ('2025-26-topps-basketball', 'SMF', 'Social Media Followback Redemption', 'insert'),
  ('2025-26-topps-basketball', 'SA2', 'Sole Ambition', 'insert'),
  ('2025-26-topps-basketball', 'HCA', 'Home Court', 'insert'),
  ('2025-26-topps-basketball', 'HG', 'Hidden Gems', 'insert'),
  ('2025-26-topps-basketball', 'SST', 'Swish And Stitch Relics', 'insert'),
  ('2025-26-topps-basketball', 'OTGA', 'Own The Game', 'insert'),
  ('2025-26-topps-basketball', 'RTO', 'Rise To The Occasion Relics', 'insert'),
  ('2025-26-topps-basketball', 'FF', 'Franchise Fabrics', 'insert'),
  ('2025-26-topps-basketball', 'FRO', 'Flagship Real One Relic', 'insert'),
  ('2025-26-topps-basketball', 'SR', 'Store Exclusive Relics', 'insert'),
  ('2025-26-topps-basketball', 'RR', 'Retail Ripper Relics', 'insert'),
  ('2025-26-topps-basketball', 'RRR', 'Rookie Roundball Remnants', 'insert'),
  ('2025-26-topps-basketball', 'WW', 'Woven Wonders Relics', 'insert'),
  ('2025-26-topps-holiday', 'base', 'Base (vétérans & rookies)', 'base'),
  ('2025-26-topps-holiday', 'BCA2', 'Base Cards II Autograph Parallel', 'autograph'),
  ('2025-26-topps-holiday', 'BCA1', 'Base Cards I Autograph Parallel', 'autograph'),
  ('2025-26-topps-holiday', 'SSB', 'Base Holiday Backs Variation Super Short Prints', 'insert'),
  ('2025-26-topps-holiday', 'SSV', 'Base Holiday Variation Super Short Prints', 'insert'),
  ('2025-26-topps-holiday', 'FF', 'Frostbite Finishers', 'insert'),
  ('2025-26-topps-holiday', 'HE', 'Hidden Elf', 'insert'),
  ('2025-26-topps-holiday', 'DCO', 'Oversized Die-Cut Ornament', 'insert'),
  ('2025-26-topps-holiday', 'PR', 'Player Relics', 'insert'),
  ('2025-26-topps-holiday', 'DPR', 'Dual Player Relics', 'insert'),
  ('2025-26-topps-holiday', 'HR', 'Holiday Relics', 'insert'),
  ('2025-26-topps-holiday', 'HSR', 'Player Holiday Shaped Relics', 'insert'),
  ('2025-26-topps-chrome', 'base', 'Base (vétérans & rookies)', 'base'),
  ('2025-26-topps-chrome', 'TAIR', 'Topps Autograph Issue Rookies', 'autograph'),
  ('2025-26-topps-chrome', 'TCAR', 'Topps Chrome Autographs Rookies', 'autograph'),
  ('2025-26-topps-chrome', 'SS', 'Signature Style', 'autograph'),
  ('2025-26-topps-chrome', 'SWS', 'Sky Write Signatures', 'autograph'),
  ('2025-26-topps-chrome', 'NS', 'Next Stop Signatures', 'autograph'),
  ('2025-26-topps-chrome', 'TCA', 'Topps Chrome Autographs', 'autograph'),
  ('2025-26-topps-chrome', 'TAU', 'Topps Autograph Issue', 'autograph'),
  ('2025-26-topps-chrome', 'FS', 'Future Stars Autographs', 'autograph'),
  ('2025-26-topps-chrome', 'CH', 'Chromographs', 'insert'),
  ('2025-26-topps-chrome', 'SMR', 'Stratospheric Signatures Rookies', 'autograph'),
  ('2025-26-topps-chrome', 'SM', 'Stratospheric Signatures', 'autograph'),
  ('2025-26-topps-chrome', 'CHR', 'Chromographs Rookie', 'insert'),
  ('2025-26-topps-chrome', 'TCA2', 'Topps Chrome Autographs II', 'autograph'),
  ('2025-26-topps-chrome', 'GLM', 'Topps Chrome Gold Logoman II', 'insert'),
  ('2025-26-topps-chrome', 'GLMR', 'Topps Chrome Gold Logoman II Autograph Relics Redemption Card', 'autograph'),
  ('2025-26-topps-chrome', 'SF', 'Sleek Finishers', 'insert'),
  ('2025-26-topps-chrome', 'CG', 'Clutch Gene', 'insert'),
  ('2025-26-topps-chrome', 'D', 'Destiny', 'insert'),
  ('2025-26-topps-chrome', 'TT', 'Tall Tales', 'insert'),
  ('2025-26-topps-chrome', 'BD', 'Ball Of Duty', 'insert'),
  ('2025-26-topps-chrome', 'GT', 'Go Time', 'insert'),
  ('2025-26-topps-chrome', 'INS', 'Instinct', 'insert'),
  ('2025-26-topps-chrome', 'GR', 'Generation Rising', 'insert'),
  ('2025-26-topps-chrome', 'IP', 'Inspirational', 'insert'),
  ('2025-26-topps-chrome', 'YQ', 'Youthquake', 'insert'),
  ('2025-26-topps-chrome', 'LD', 'Loading', 'insert'),
  ('2025-26-topps-chrome', 'AC', 'Activators', 'insert'),
  ('2025-26-topps-chrome', 'SY', 'Serenity', 'insert'),
  ('2025-26-topps-chrome', 'VS', 'Voices', 'insert'),
  ('2025-26-topps-chrome', 'XW', 'Xs And Whoas', 'insert'),
  ('2025-26-topps-chrome', 'FAN', 'Fanatical', 'insert'),
  ('2025-26-topps-chrome', 'SS2', 'Sapphire Selections', 'insert'),
  ('2025-26-topps-chrome', 'PD', 'Patented', 'insert'),
  ('2025-26-topps-chrome', 'PX', 'Paradox', 'insert'),
  ('2025-26-topps-chrome', 'GC', 'Glass Canvas', 'insert'),
  ('2025-26-topps-chrome', 'RS', 'Rock Stars', 'insert'),
  ('2025-26-topps-chrome', 'AD', 'Advisory', 'insert'),
  ('2025-26-topps-chrome', 'H', 'Helix', 'insert'),
  ('2025-26-topps-chrome', 'UV', 'Ultra VIolet', 'insert'),
  ('2025-26-topps-chrome', 'LG', 'Lets Go', 'insert'),
  ('2025-26-topps-chrome', 'RR', 'Radiating Rookies', 'insert'),
  ('2025-26-topps-chrome', 'IS', 'Infinite Sapphire', 'insert'),
  ('2025-26-topps-chrome', 'FIN', 'Finals', 'insert'),
  ('2025-26-topps-chrome', 'TCGL', 'Topps Chrome Gold Logoman', 'insert'),
  ('2025-26-topps-chrome', 'TCGR', 'Topps Chrome Gold Logoman Relics Redemption Card', 'insert'),
  ('2025-26-topps-chrome-sapphire', 'base', 'Base Sapphire', 'base'),
  ('2025-26-topps-chrome-sapphire', 'TCAR', 'Topps Chrome Autographs Rookies', 'autograph'),
  ('2025-26-topps-chrome-sapphire', 'SS', 'Signature Style', 'autograph'),
  ('2025-26-topps-chrome-sapphire', 'SWS', 'Sky-Write Signatures', 'autograph'),
  ('2025-26-topps-chrome-sapphire', 'NS', 'Next Stop Signatures', 'autograph'),
  ('2025-26-topps-chrome-sapphire', 'TCA', 'Topps Chrome Autographs', 'autograph'),
  ('2025-26-topps-chrome-sapphire', 'TAIR', 'Topps Autograph Issue Rookies', 'autograph'),
  ('2025-26-topps-chrome-sapphire', 'TCA2', 'Topps Chrome Autographs II', 'autograph'),
  ('2025-26-topps-chrome-sapphire', 'SSEL', 'Sapphire Selections', 'insert'),
  ('2025-26-topps-chrome-sapphire', 'IS', 'Infinite Sapphire', 'insert'),
  ('2025-26-topps-midnight', 'base', 'Base', 'base'),
  ('2025-26-topps-midnight', 'SM', 'Stroke Of Midnight Autographs', 'autograph'),
  ('2025-26-topps-midnight', 'RHS', 'Rookie Horizon Signatures', 'autograph'),
  ('2025-26-topps-midnight', 'RJA', 'Rookie Jersey Autographs', 'autograph'),
  ('2025-26-topps-midnight', 'MS', 'Midnight Sun Signatures', 'autograph'),
  ('2025-26-topps-midnight', 'MO', 'Midnight Oil Marks', 'insert'),
  ('2025-26-topps-midnight', 'DM', 'Dark Marks', 'insert'),
  ('2025-26-topps-midnight', 'SMR', 'Stroke Of Midnight Autographs Rookies', 'autograph'),
  ('2025-26-topps-midnight', 'DMA', 'Dark Matter Autographs', 'autograph'),
  ('2025-26-topps-midnight', 'MSR', 'Midnight Sun Signatures Rookies', 'autograph'),
  ('2025-26-topps-midnight', 'DMAR', 'Dark Matter Autographs Rookies', 'autograph'),
  ('2025-26-topps-midnight', 'DMR', 'Dark Marks Rookies', 'insert'),
  ('2025-26-topps-midnight', 'MOR', 'Midnight Oil Marks Rookies', 'insert'),
  ('2025-26-topps-midnight', 'MF', 'Moonfall', 'insert'),
  ('2025-26-topps-midnight', 'NO', 'Night Owls', 'insert'),
  ('2025-26-topps-midnight', 'IN', 'Insomnia', 'insert'),
  ('2025-26-topps-midnight', 'DD', 'Daydreamers', 'insert'),
  ('2025-26-topps-midnight', 'NS', 'Night Shade', 'insert'),
  ('2025-26-topps-midnight', 'DL', 'Dreamland', 'insert'),
  ('2025-26-topps-midnight', 'NV', 'Night VIsion', 'insert'),
  ('2025-26-topps-midnight', 'TL', 'Twilight', 'insert'),
  ('2025-26-topps-finest', 'base', 'Base (Common/Uncommon/Rare)', 'base'),
  ('2025-26-topps-finest', 'FAU', 'Autographs', 'autograph'),
  ('2025-26-topps-finest', 'BA', 'Baseline Autographs', 'autograph'),
  ('2025-26-topps-finest', 'MA', 'Masters Autographs', 'autograph'),
  ('2025-26-topps-finest', 'RFA', 'Rookie Autographs', 'autograph'),
  ('2025-26-topps-finest', 'CS', 'Colossal Shots Autographs', 'autograph'),
  ('2025-26-topps-finest', 'ESG', 'Electrifying Signatures', 'autograph'),
  ('2025-26-topps-finest', 'A', 'Arrivals', 'insert'),
  ('2025-26-topps-finest', 'F', 'First', 'insert'),
  ('2025-26-topps-finest', 'M', 'Muse', 'insert'),
  ('2025-26-topps-finest', 'FI', 'Finishers', 'insert'),
  ('2025-26-topps-finest', 'AU', 'Aura', 'insert'),
  ('2025-26-topps-finest', 'H', 'Headliners', 'insert'),
  ('2025-26-topps-finest', 'TM', 'The Man', 'insert'),
  ('2025-26-topps-finest', 'P', 'Pulse', 'insert'),
  ('2025-26-topps-three', 'base', 'Base', 'base'),
  ('2025-26-topps-three', 'V3A', 'Veteran 3 Patch Autographs', 'autograph'),
  ('2025-26-topps-three', 'TD', 'Thunderdunk Signatures', 'autograph'),
  ('2025-26-topps-three', 'GT', 'Game Time Graphs', 'insert'),
  ('2025-26-topps-three', 'RS', 'Raindrops Signatures', 'autograph'),
  ('2025-26-topps-three', 'TP', 'Triple Power Autographs', 'autograph'),
  ('2025-26-topps-three', 'SS', 'Serendipitous Sigs', 'insert'),
  ('2025-26-topps-three', 'HM', 'Hit The Mark', 'insert'),
  ('2025-26-topps-three', 'RM', 'Re-Markable', 'insert'),
  ('2025-26-topps-three', 'RRA', 'Rookie Relics Autographs', 'autograph'),
  ('2025-26-topps-three', 'RV', 'Rookie-Verse Autographs', 'autograph'),
  ('2025-26-topps-three', 'RA', 'Rookie Autographs', 'autograph'),
  ('2025-26-topps-three', 'FS', 'Full Court Signs', 'autograph'),
  ('2025-26-topps-three', 'FFR', 'Fresh Force Relic Autographs', 'autograph'),
  ('2025-26-topps-three', 'NF', 'Next Feature Signatures', 'autograph'),
  ('2025-26-topps-three', 'TRA', 'Triple Relics Autographs', 'autograph'),
  ('2025-26-topps-three', 'RPH', 'Rookie 3 Patch Autographs Horizontal', 'autograph'),
  ('2025-26-topps-three', 'RPV', 'Rookie 3 Patch Autographs Vertical', 'autograph'),
  ('2025-26-topps-three', 'RAP', 'Relics Autographs Prime', 'autograph'),
  ('2025-26-topps-three', 'RR', 'Rim Reapers Signatures', 'autograph'),
  ('2025-26-topps-three', 'QG', 'Quest For Glory Autographs', 'autograph'),
  ('2025-26-topps-three', 'CD', 'City Drip Signatures', 'autograph'),
  ('2025-26-topps-three', 'IW', 'Ice Water', 'insert'),
  ('2025-26-topps-three', 'FP', 'Flight Path', 'insert'),
  ('2025-26-topps-three', 'AR', 'Architects', 'insert'),
  ('2025-26-topps-three', '3D', '3 And D', 'insert'),
  ('2025-26-topps-three', 'MD', 'Monsters Of The Deep', 'insert'),
  ('2025-26-topps-three', 'PAINT', 'The Paint', 'insert')
on conflict (set_id, id) do update set name = excluded.name, type = excluded.type;

commit;
