-- =====================================================================
-- Hoops Archive -- migration 0003c2 : cartes 2025-26-topps-holiday (partie 2/2)
-- FICHIER GENERE AUTOMATIQUEMENT -- ne pas editer a la main.
-- Relancable sans risque (ON CONFLICT DO UPDATE).
-- =====================================================================

begin;

-- Cartes (105)
insert into public.cards (set_id, card_code, subset, player, team, player_id, team_id, season, rookie, variant, jersey_number) values
  ('2025-26-topps-holiday', 'PR-JHA', 'PR', 'James Harden', 'Los Angeles Clippers', 'james-harden', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-JHO', 'PR', 'Jrue Holiday', 'Boston Celtics', 'jrue-holiday', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-JI', 'PR', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-JJ', 'PR', 'Jaime Jaquez Jr.', 'Miami Heat', 'jaime-jaquez-jr', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-JJJ', 'PR', 'Jalen Johnson', 'Atlanta Hawks', 'jalen-johnson', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-JM', 'PR', 'Ja Morant', 'Memphis Grizzlies', 'ja-morant', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-JO', 'PR', 'Johni Broome', 'Philadelphia 76ers', 'johni-broome', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-JP', 'PR', 'Jordan Poole', 'Washington Wizards', 'jordan-poole', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-JR', 'PR', 'Jase Richardson', 'Orlando Magic', 'jase-richardson', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-JS', 'PR', 'Jeremy Sochan', 'San Antonio Spurs', 'jeremy-sochan', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-JSU', 'PR', 'Jalen Suggs', 'Orlando Magic', 'jalen-suggs', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-JW', 'PR', 'Jamir Watkins', 'Washington Wizards', 'jamir-watkins', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-KB', 'PR', 'Koby Brea', 'Phoenix Suns', 'koby-brea', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-KG', 'PR', 'Keyonte George', 'Utah Jazz', 'keyonte-george', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-KJ', 'PR', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-KK', 'PR', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-KM', 'PR', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-KO', 'PR', 'Kam Jones', 'Indiana Pacers', 'kam-jones', 'indiana-pacers', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-LB', 'PR', 'LaMelo Ball', 'Charlotte Hornets', 'lamelo-ball', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-LM', 'PR', 'Liam McNeeley', 'Charlotte Hornets', 'liam-mcneeley', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-MC', 'PR', 'Mike Conley', 'Minnesota Timberwolves', 'mike-conley', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-MP', 'PR', 'Micah Peavy', 'New Orleans Pelicans', 'micah-peavy', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-MPJ', 'PR', 'Michael Porter Jr.', 'Denver Nuggets', 'michael-porter-jr', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-MR', 'PR', 'Maxime Raynaud', 'Sacramento Kings', 'maxime-raynaud', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-MT', 'PR', 'Myles Turner', 'Indiana Pacers', 'myles-turner', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-NB', 'PR', 'Nicolas Batum', 'Los Angeles Clippers', 'nicolas-batum', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-NC', 'PR', 'Noah Clowney', 'Brooklyn Nets', 'noah-clowney', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-NCL', 'PR', 'Nic Claxton', 'Brooklyn Nets', 'nic-claxton', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-ND', 'PR', 'Noah Penda', 'Orlando Magic', 'noah-penda', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-NE', 'PR', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-NI', 'PR', 'Nique Clifford', 'Sacramento Kings', 'nique-clifford', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-NP', 'PR', 'Norman Powell', 'Los Angeles Clippers', 'norman-powell', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-NT', 'PR', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-OO', 'PR', 'Onyeka Okongwu', 'Atlanta Hawks', 'onyeka-okongwu', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-OT', 'PR', 'Obi Toppin', 'Indiana Pacers', 'obi-toppin', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-PG', 'PR', 'Paul George', 'Philadelphia 76ers', 'paul-george', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-PW', 'PR', 'Patrick Williams', 'Chicago Bulls', 'patrick-williams', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-RB', 'PR', 'RJ Barrett', 'Toronto Raptors', 'rj-barrett', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-RF', 'PR', 'Rasheer Fleming', 'Phoenix Suns', 'rasheer-fleming', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-RG', 'PR', 'Rudy Gobert', 'Minnesota Timberwolves', 'rudy-gobert', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-RK', 'PR', 'Ryan Kalkbrenner', 'Charlotte Hornets', 'ryan-kalkbrenner', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-SH', 'PR', 'Scoot Henderson', 'Portland Trail Blazers', 'scoot-henderson', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-SJ', 'PR', 'Sion James', 'Charlotte Hornets', 'sion-james', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-TE', 'PR', 'Tari Eason', 'Houston Rockets', 'tari-eason', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-TH', 'PR', 'Tobias Harris', 'Detroit Pistons', 'tobias-harris', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-THE', 'PR', 'Tyler Herro', 'Miami Heat', 'tyler-herro', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-TO', 'PR', 'Tyrese Proctor', 'Cleveland Cavaliers', 'tyrese-proctor', 'cleveland-cavaliers', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-TS', 'PR', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-TY', 'PR', 'Trae Young', 'Atlanta Hawks', 'trae-young', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-WC', 'PR', 'Wendell Carter Jr.', 'Orlando Magic', 'wendell-carter-jr', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'PR-WJ', 'PR', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-WR', 'PR', 'Will Riley', 'Washington Wizards', 'will-riley', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-YH', 'PR', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-YK', 'PR', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers', 'yanic-konan-niederhauser', 'los-angeles-clippers', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'PR-ZR', 'PR', 'Zaccharie Risacher', 'Atlanta Hawks', 'zaccharie-risacher', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-AB', 'SSB', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-AE', 'SSB', 'Anthony Edwards', 'Minnesota Timberwolves', 'anthony-edwards', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-AT', 'SSB', 'Amen Thompson', 'Houston Rockets', 'amen-thompson', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-CC', 'SSB', 'Cade Cunningham', 'Detroit Pistons', 'cade-cunningham', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-CF', 'SSB', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-CM', 'SSB', 'Collin Murray-Boyles', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-DB', 'SSB', 'Devin Booker', 'Phoenix Suns', 'devin-booker', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-DH', 'SSB', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-DM', 'SSB', 'Donovan Mitchell', 'Cleveland Cavaliers', 'donovan-mitchell', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-ED', 'SSB', 'Egor Dëmin', 'Brooklyn Nets', 'egor-demin', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-GA', 'SSB', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-JB', 'SSB', 'Jalen Brunson', 'New York Knicks', 'jalen-brunson', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-JF', 'SSB', 'Jeremiah Fears', 'New Orleans Pelicans', 'jeremiah-fears', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-JM', 'SSB', 'Ja Morant', 'Memphis Grizzlies', 'ja-morant', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-JT', 'SSB', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-KK', 'SSB', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-KM', 'SSB', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-LB', 'SSB', 'LaMelo Ball', 'Charlotte Hornets', 'lamelo-ball', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-LBJ', 'SSB', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-PB', 'SSB', 'Paolo Banchero', 'Orlando Magic', 'paolo-banchero', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-SC', 'SSB', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-SGA', 'SSB', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSB-TJ', 'SSB', 'Tre Johnson III', 'Washington Wizards', 'tre-johnson-iii', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-VE', 'SSB', 'VJ Edgecombe', 'Philadelphia 76ers', 'vj-edgecombe', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSB-VW', 'SSB', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-AE', 'SSV', 'James Harden', 'Los Angeles Clippers', 'james-harden', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-AT', 'SSV', 'Kyrie Irving', 'Dallas Mavericks', 'kyrie-irving', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-CB', 'SSV', 'Carter Bryant', 'San Antonio Spurs', 'carter-bryant', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSV-CC', 'SSV', 'Donovan Mitchell', 'Cleveland Cavaliers', 'donovan-mitchell', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-CO', 'SSV', 'Cedric Coward', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSV-DM', 'SSV', 'Jalen Williams', 'Oklahoma City Thunder', 'jalen-williams', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-DQ', 'SSV', 'Derik Queen', 'New Orleans Pelicans', 'derik-queen', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSV-FW', 'SSV', 'Franz Wagner', 'Orlando Magic', 'franz-wagner', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-GA', 'SSV', 'Alex Sarr', 'Washington Wizards', 'alex-sarr', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-JB', 'SSV', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSV-JM', 'SSV', 'Kevin Durant', 'Houston Rockets', 'kevin-durant', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-JT', 'SSV', 'Jaylen Brown', 'Boston Celtics', 'jaylen-brown', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-KJ', 'SSV', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSV-LB', 'SSV', 'Nikola Jokić', 'Denver Nuggets', 'nikola-jokic', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-LBJ', 'SSV', 'Damian Lillard', 'Milwaukee Bucks', 'damian-lillard', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-NE', 'SSV', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSV-NJ', 'SSV', 'Jimmy Butler III', 'Golden State Warriors', 'jimmy-butler-iii', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-NT', 'SSV', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSV-SA', 'SSV', 'Stephon Castle', 'San Antonio Spurs', 'stephon-castle', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-SC', 'SSV', 'Jalen Brunson', 'New York Knicks', 'jalen-brunson', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-TM', 'SSV', 'Tyler Herro', 'Miami Heat', 'tyler-herro', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-TS', 'SSV', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSV-VW', 'SSV', 'Trae Young', 'Atlanta Hawks', 'trae-young', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-holiday', 'SSV-WC', 'SSV', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-holiday', 'SSV-YH', 'SSV', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null)
on conflict (set_id, card_code) do update set
  subset = excluded.subset, player = excluded.player, team = excluded.team,
  player_id = excluded.player_id, team_id = excluded.team_id, season = excluded.season,
  rookie = excluded.rookie, variant = excluded.variant, jersey_number = excluded.jersey_number;

-- Associations carte/joueur (105)
insert into public.card_players (set_id, card_code, slot, player, player_id, team, team_id, season) values
  ('2025-26-topps-holiday', 'PR-JHA', 1, 'James Harden', 'james-harden', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JHO', 1, 'Jrue Holiday', 'jrue-holiday', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JI', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JJ', 1, 'Jaime Jaquez Jr.', 'jaime-jaquez-jr', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JJJ', 1, 'Jalen Johnson', 'jalen-johnson', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JM', 1, 'Ja Morant', 'ja-morant', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JO', 1, 'Johni Broome', 'johni-broome', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JP', 1, 'Jordan Poole', 'jordan-poole', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JR', 1, 'Jase Richardson', 'jase-richardson', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JS', 1, 'Jeremy Sochan', 'jeremy-sochan', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JSU', 1, 'Jalen Suggs', 'jalen-suggs', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-holiday', 'PR-JW', 1, 'Jamir Watkins', 'jamir-watkins', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-holiday', 'PR-KB', 1, 'Koby Brea', 'koby-brea', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-holiday', 'PR-KG', 1, 'Keyonte George', 'keyonte-george', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-holiday', 'PR-KJ', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-holiday', 'PR-KK', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-KM', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-holiday', 'PR-KO', 1, 'Kam Jones', 'kam-jones', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-LB', 1, 'LaMelo Ball', 'lamelo-ball', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-LM', 1, 'Liam McNeeley', 'liam-mcneeley', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-MC', 1, 'Mike Conley', 'mike-conley', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-holiday', 'PR-MP', 1, 'Micah Peavy', 'micah-peavy', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-holiday', 'PR-MPJ', 1, 'Michael Porter Jr.', 'michael-porter-jr', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-MR', 1, 'Maxime Raynaud', 'maxime-raynaud', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-holiday', 'PR-MT', 1, 'Myles Turner', 'myles-turner', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-NB', 1, 'Nicolas Batum', 'nicolas-batum', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-NC', 1, 'Noah Clowney', 'noah-clowney', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-NCL', 1, 'Nic Claxton', 'nic-claxton', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-ND', 1, 'Noah Penda', 'noah-penda', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-holiday', 'PR-NE', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-holiday', 'PR-NI', 1, 'Nique Clifford', 'nique-clifford', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-holiday', 'PR-NP', 1, 'Norman Powell', 'norman-powell', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-NT', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-OO', 1, 'Onyeka Okongwu', 'onyeka-okongwu', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-holiday', 'PR-OT', 1, 'Obi Toppin', 'obi-toppin', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-PG', 1, 'Paul George', 'paul-george', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-PW', 1, 'Patrick Williams', 'patrick-williams', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-holiday', 'PR-RB', 1, 'RJ Barrett', 'rj-barrett', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-holiday', 'PR-RF', 1, 'Rasheer Fleming', 'rasheer-fleming', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-holiday', 'PR-RG', 1, 'Rudy Gobert', 'rudy-gobert', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-holiday', 'PR-RK', 1, 'Ryan Kalkbrenner', 'ryan-kalkbrenner', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-SH', 1, 'Scoot Henderson', 'scoot-henderson', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-SJ', 1, 'Sion James', 'sion-james', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-TE', 1, 'Tari Eason', 'tari-eason', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-holiday', 'PR-TH', 1, 'Tobias Harris', 'tobias-harris', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-holiday', 'PR-THE', 1, 'Tyler Herro', 'tyler-herro', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-holiday', 'PR-TO', 1, 'Tyrese Proctor', 'tyrese-proctor', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-TS', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-holiday', 'PR-TY', 1, 'Trae Young', 'trae-young', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-holiday', 'PR-WC', 1, 'Wendell Carter Jr.', 'wendell-carter-jr', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-holiday', 'PR-WJ', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-holiday', 'PR-WR', 1, 'Will Riley', 'will-riley', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-holiday', 'PR-YH', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-YK', 1, 'Yanic Konan-Niederhäuser', 'yanic-konan-niederhauser', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-holiday', 'PR-ZR', 1, 'Zaccharie Risacher', 'zaccharie-risacher', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-AB', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-AE', 1, 'Anthony Edwards', 'anthony-edwards', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-AT', 1, 'Amen Thompson', 'amen-thompson', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-CC', 1, 'Cade Cunningham', 'cade-cunningham', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-CF', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-CM', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-DB', 1, 'Devin Booker', 'devin-booker', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-DH', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-DM', 1, 'Donovan Mitchell', 'donovan-mitchell', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-ED', 1, 'Egor Dëmin', 'egor-demin', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-GA', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-JB', 1, 'Jalen Brunson', 'jalen-brunson', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-JF', 1, 'Jeremiah Fears', 'jeremiah-fears', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-JM', 1, 'Ja Morant', 'ja-morant', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-JT', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-KK', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-KM', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-LB', 1, 'LaMelo Ball', 'lamelo-ball', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-LBJ', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-PB', 1, 'Paolo Banchero', 'paolo-banchero', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-SC', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-SGA', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-TJ', 1, 'Tre Johnson III', 'tre-johnson-iii', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-VE', 1, 'VJ Edgecombe', 'vj-edgecombe', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-holiday', 'SSB-VW', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-AE', 1, 'James Harden', 'james-harden', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-AT', 1, 'Kyrie Irving', 'kyrie-irving', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-CB', 1, 'Carter Bryant', 'carter-bryant', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-CC', 1, 'Donovan Mitchell', 'donovan-mitchell', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-CO', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-DM', 1, 'Jalen Williams', 'jalen-williams', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-DQ', 1, 'Derik Queen', 'derik-queen', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-FW', 1, 'Franz Wagner', 'franz-wagner', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-GA', 1, 'Alex Sarr', 'alex-sarr', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-JB', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-JM', 1, 'Kevin Durant', 'kevin-durant', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-JT', 1, 'Jaylen Brown', 'jaylen-brown', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-KJ', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-LB', 1, 'Nikola Jokić', 'nikola-jokic', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-LBJ', 1, 'Damian Lillard', 'damian-lillard', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-NE', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-NJ', 1, 'Jimmy Butler III', 'jimmy-butler-iii', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-NT', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-SA', 1, 'Stephon Castle', 'stephon-castle', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-SC', 1, 'Jalen Brunson', 'jalen-brunson', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-TM', 1, 'Tyler Herro', 'tyler-herro', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-TS', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-VW', 1, 'Trae Young', 'trae-young', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-WC', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-holiday', 'SSV-YH', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26')
on conflict (set_id, card_code, slot) do update set
  player = excluded.player, player_id = excluded.player_id, team = excluded.team,
  team_id = excluded.team_id, season = excluded.season;

commit;
