-- =====================================================================
-- Hoops Archive -- migration 0003f2 : cartes 2025-26-topps-midnight (partie 2/2)
-- FICHIER GENERE AUTOMATIQUEMENT -- ne pas editer a la main.
-- Relancable sans risque (ON CONFLICT DO UPDATE).
-- =====================================================================

begin;

-- Cartes (93)
insert into public.cards (set_id, card_code, subset, player, team, player_id, team_id, season, rookie, variant, jersey_number) values
  ('2025-26-topps-midnight', 'RJA-LM', 'RJA', 'Liam McNeeley', 'Charlotte Hornets', 'liam-mcneeley', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-MR', 'RJA', 'Maxime Raynaud', 'Sacramento Kings', 'maxime-raynaud', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-NC', 'RJA', 'Nique Clifford', 'Sacramento Kings', 'nique-clifford', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-NE', 'RJA', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-NP', 'RJA', 'Noah Penda', 'Orlando Magic', 'noah-penda', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-NT', 'RJA', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-RF', 'RJA', 'Rasheer Fleming', 'Phoenix Suns', 'rasheer-fleming', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-RK', 'RJA', 'Ryan Kalkbrenner', 'Charlotte Hornets', 'ryan-kalkbrenner', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-TP', 'RJA', 'Tyrese Proctor', 'Cleveland Cavaliers', 'tyrese-proctor', 'cleveland-cavaliers', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-TS', 'RJA', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-WC', 'RJA', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-WR', 'RJA', 'Will Riley', 'Washington Wizards', 'will-riley', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-YH', 'RJA', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'RJA-YK', 'RJA', 'Yanic Konan-Niederhäuser', 'Los Angeles Clippers', 'yanic-konan-niederhauser', 'los-angeles-clippers', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SM-AB', 'SM', 'Adem Bona', 'Philadelphia 76ers', 'adem-bona', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-AD', 'SM', 'Ayo Dosunmu', 'Chicago Bulls', 'ayo-dosunmu', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-AE', 'SM', 'Alex English', 'Denver Nuggets', 'alex-english', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-AM', 'SM', 'Ajay Mitchell', 'Oklahoma City Thunder', 'ajay-mitchell', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-AN', 'SM', 'Aaron Nesmith', 'Indiana Pacers', 'aaron-nesmith', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-AR', 'SM', 'Antonio Reeves', 'New Orleans Pelicans', 'antonio-reeves', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-BM', 'SM', 'Brandon Miller', 'Charlotte Hornets', 'brandon-miller', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-BS', 'SM', 'Ben Sheppard', 'Indiana Pacers', 'ben-sheppard', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-CC', 'SM', 'Cam Christie', 'Los Angeles Clippers', 'cam-christie', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-CM', 'SM', 'Calvin Murphy', 'Houston Rockets', 'calvin-murphy', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-CS', 'SM', 'Cam Spencer', 'Memphis Grizzlies', 'cam-spencer', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-DG', 'SM', 'Daniel Gafford', 'Dallas Mavericks', 'daniel-gafford', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-DH', 'SM', 'DaRon Holmes II', 'Denver Nuggets', 'daron-holmes-ii', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-DS', 'SM', 'Day''ron Sharpe', 'Brooklyn Nets', 'dayron-sharpe', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-DW', 'SM', 'Dominique Wilkins', 'Atlanta Hawks', 'dominique-wilkins', 'atlanta-hawks', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-FW', 'SM', 'Franz Wagner', 'Orlando Magic', 'franz-wagner', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-GAN', 'SM', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-GG', 'SM', 'George Gervin', 'San Antonio Spurs', 'george-gervin', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-HI', 'SM', 'Harrison Ingram', 'San Antonio Spurs', 'harrison-ingram', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-JH', 'SM', 'Josh Hart', 'New York Knicks', 'josh-hart', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-JL', 'SM', 'Jake LaRavia', 'Sacramento Kings', 'jake-laravia', 'sacramento-kings', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-JOW', 'SM', 'Jordan Walsh', 'Boston Celtics', 'jordan-walsh', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-JP', 'SM', 'Jalen Pickett', 'Denver Nuggets', 'jalen-pickett', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-JS', 'SM', 'Jamal Shead', 'Toronto Raptors', 'jamal-shead', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-JW', 'SM', 'Jalen Wilson', 'Brooklyn Nets', 'jalen-wilson', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-JWE', 'SM', 'Jaylen Wells', 'Memphis Grizzlies', 'jaylen-wells', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-KH', 'SM', 'Kevin Huerter', 'Chicago Bulls', 'kevin-huerter', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-MC', 'SM', 'Maurice Cheeks', 'Philadelphia 76ers', 'maurice-cheeks', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-MS', 'SM', 'Marcus Sasser', 'Detroit Pistons', 'marcus-sasser', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-NJ', 'SM', 'Nikola Jokić', 'Denver Nuggets', 'nikola-jokic', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-OI', 'SM', 'Oso Ighodaro', 'Phoenix Suns', 'oso-ighodaro', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-PL', 'SM', 'Pelle Larsson', 'Miami Heat', 'pelle-larsson', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-PP', 'SM', 'Payton Pritchard', 'Boston Celtics', 'payton-pritchard', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-PS', 'SM', 'Pascal Siakam', 'Indiana Pacers', 'pascal-siakam', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-QP', 'SM', 'Quinten Post', 'Golden State Warriors', 'quinten-post', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-RJ', 'SM', 'Reggie Jackson', 'Philadelphia 76ers', 'reggie-jackson', 'philadelphia-76ers', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-RJE', 'SM', 'Richard Jefferson', 'Brooklyn Nets', 'richard-jefferson', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-RW', 'SM', 'Rasheed Wallace', 'Detroit Pistons', 'rasheed-wallace', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-TH', 'SM', 'Tim Hardaway', 'Miami Heat', 'tim-hardaway', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-TK', 'SM', 'Tyler Kolek', 'New York Knicks', 'tyler-kolek', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-TN', 'SM', 'Tristen Newton', 'Minnesota Timberwolves', 'tristen-newton', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-TS', 'SM', 'Tristan da Silva', 'Orlando Magic', 'tristan-da-silva', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SM-ZC', 'SM', 'Zach Collins', 'Chicago Bulls', 'zach-collins', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'SMR-AN', 'SMR', 'Asa Newell', 'Atlanta Hawks', 'asa-newell', 'atlanta-hawks', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-AT', 'SMR', 'Adou Thiero', 'Los Angeles Lakers', 'adou-thiero', 'los-angeles-lakers', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-BB', 'SMR', 'Brooks Barnhizer', 'Oklahoma City Thunder', 'brooks-barnhizer', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-BS', 'SMR', 'Ben Saraf', 'Brooklyn Nets', 'ben-saraf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-CC', 'SMR', 'Cedric Coward', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-CL', 'SMR', 'Chaz Lanier', 'Detroit Pistons', 'chaz-lanier', 'detroit-pistons', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-DH', 'SMR', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-DP', 'SMR', 'Drake Powell', 'Brooklyn Nets', 'drake-powell', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-DW', 'SMR', 'Danny Wolf', 'Brooklyn Nets', 'danny-wolf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-JB', 'SMR', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-JBR', 'SMR', 'Johni Broome', 'Philadelphia 76ers', 'johni-broome', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-JR', 'SMR', 'Jase Richardson', 'Orlando Magic', 'jase-richardson', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-KB', 'SMR', 'Koby Brea', 'Phoenix Suns', 'koby-brea', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-KJ', 'SMR', 'Kam Jones', 'Indiana Pacers', 'kam-jones', 'indiana-pacers', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-KM', 'SMR', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-LM', 'SMR', 'Liam McNeeley', 'Charlotte Hornets', 'liam-mcneeley', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-MP', 'SMR', 'Micah Peavy', 'New Orleans Pelicans', 'micah-peavy', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-RK', 'SMR', 'Ryan Kalkbrenner', 'Charlotte Hornets', 'ryan-kalkbrenner', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-SJ', 'SMR', 'Sion James', 'Charlotte Hornets', 'sion-james', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-WC', 'SMR', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'SMR-WR', 'SMR', 'Will Riley', 'Washington Wizards', 'will-riley', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'TL-1', 'TL', 'LeBron James', 'Los Angeles Lakers', 'lebron-james', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'TL-10', 'TL', 'Giannis Antetokounmpo', 'Milwaukee Bucks', 'giannis-antetokounmpo', 'milwaukee-bucks', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'TL-11', 'TL', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'TL-12', 'TL', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'TL-13', 'TL', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'TL-14', 'TL', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'TL-15', 'TL', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-midnight', 'TL-2', 'TL', 'Stephen Curry', 'Golden State Warriors', 'stephen-curry', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'TL-3', 'TL', 'Anthony Edwards', 'Minnesota Timberwolves', 'anthony-edwards', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'TL-4', 'TL', 'Nikola Jokić', 'Denver Nuggets', 'nikola-jokic', 'denver-nuggets', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'TL-5', 'TL', 'Shai Gilgeous-Alexander', 'Oklahoma City Thunder', 'shai-gilgeous-alexander', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'TL-6', 'TL', 'Tyrese Haliburton', 'Indiana Pacers', 'tyrese-haliburton', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'TL-7', 'TL', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'TL-8', 'TL', 'Kevin Durant', 'Phoenix Suns', 'kevin-durant', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-midnight', 'TL-9', 'TL', 'Jayson Tatum', 'Boston Celtics', 'jayson-tatum', 'boston-celtics', '2025-26', false, null, null)
on conflict (set_id, card_code) do update set
  subset = excluded.subset, player = excluded.player, team = excluded.team,
  player_id = excluded.player_id, team_id = excluded.team_id, season = excluded.season,
  rookie = excluded.rookie, variant = excluded.variant, jersey_number = excluded.jersey_number;

-- Associations carte/joueur (93)
insert into public.card_players (set_id, card_code, slot, player, player_id, team, team_id, season) values
  ('2025-26-topps-midnight', 'RJA-LM', 1, 'Liam McNeeley', 'liam-mcneeley', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-MR', 1, 'Maxime Raynaud', 'maxime-raynaud', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-NC', 1, 'Nique Clifford', 'nique-clifford', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-NE', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-NP', 1, 'Noah Penda', 'noah-penda', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-NT', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-RF', 1, 'Rasheer Fleming', 'rasheer-fleming', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-RK', 1, 'Ryan Kalkbrenner', 'ryan-kalkbrenner', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-TP', 1, 'Tyrese Proctor', 'tyrese-proctor', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-TS', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-WC', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-WR', 1, 'Will Riley', 'will-riley', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-YH', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-midnight', 'RJA-YK', 1, 'Yanic Konan-Niederhäuser', 'yanic-konan-niederhauser', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-midnight', 'SM-AB', 1, 'Adem Bona', 'adem-bona', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-midnight', 'SM-AD', 1, 'Ayo Dosunmu', 'ayo-dosunmu', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-midnight', 'SM-AE', 1, 'Alex English', 'alex-english', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-midnight', 'SM-AM', 1, 'Ajay Mitchell', 'ajay-mitchell', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-midnight', 'SM-AN', 1, 'Aaron Nesmith', 'aaron-nesmith', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-midnight', 'SM-AR', 1, 'Antonio Reeves', 'antonio-reeves', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-midnight', 'SM-BM', 1, 'Brandon Miller', 'brandon-miller', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-midnight', 'SM-BS', 1, 'Ben Sheppard', 'ben-sheppard', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-midnight', 'SM-CC', 1, 'Cam Christie', 'cam-christie', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-midnight', 'SM-CM', 1, 'Calvin Murphy', 'calvin-murphy', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-midnight', 'SM-CS', 1, 'Cam Spencer', 'cam-spencer', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-midnight', 'SM-DG', 1, 'Daniel Gafford', 'daniel-gafford', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-midnight', 'SM-DH', 1, 'DaRon Holmes II', 'daron-holmes-ii', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-midnight', 'SM-DS', 1, 'Day''ron Sharpe', 'dayron-sharpe', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-midnight', 'SM-DW', 1, 'Dominique Wilkins', 'dominique-wilkins', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-midnight', 'SM-FW', 1, 'Franz Wagner', 'franz-wagner', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-midnight', 'SM-GAN', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-midnight', 'SM-GG', 1, 'George Gervin', 'george-gervin', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-midnight', 'SM-HI', 1, 'Harrison Ingram', 'harrison-ingram', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-midnight', 'SM-JH', 1, 'Josh Hart', 'josh-hart', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-midnight', 'SM-JL', 1, 'Jake LaRavia', 'jake-laravia', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-midnight', 'SM-JOW', 1, 'Jordan Walsh', 'jordan-walsh', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-midnight', 'SM-JP', 1, 'Jalen Pickett', 'jalen-pickett', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-midnight', 'SM-JS', 1, 'Jamal Shead', 'jamal-shead', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-midnight', 'SM-JW', 1, 'Jalen Wilson', 'jalen-wilson', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-midnight', 'SM-JWE', 1, 'Jaylen Wells', 'jaylen-wells', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-midnight', 'SM-KH', 1, 'Kevin Huerter', 'kevin-huerter', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-midnight', 'SM-MC', 1, 'Maurice Cheeks', 'maurice-cheeks', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-midnight', 'SM-MS', 1, 'Marcus Sasser', 'marcus-sasser', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-midnight', 'SM-NJ', 1, 'Nikola Jokić', 'nikola-jokic', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-midnight', 'SM-OI', 1, 'Oso Ighodaro', 'oso-ighodaro', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-midnight', 'SM-PL', 1, 'Pelle Larsson', 'pelle-larsson', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-midnight', 'SM-PP', 1, 'Payton Pritchard', 'payton-pritchard', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-midnight', 'SM-PS', 1, 'Pascal Siakam', 'pascal-siakam', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-midnight', 'SM-QP', 1, 'Quinten Post', 'quinten-post', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-midnight', 'SM-RJ', 1, 'Reggie Jackson', 'reggie-jackson', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-midnight', 'SM-RJE', 1, 'Richard Jefferson', 'richard-jefferson', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-midnight', 'SM-RW', 1, 'Rasheed Wallace', 'rasheed-wallace', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-midnight', 'SM-TH', 1, 'Tim Hardaway', 'tim-hardaway', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-midnight', 'SM-TK', 1, 'Tyler Kolek', 'tyler-kolek', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-midnight', 'SM-TN', 1, 'Tristen Newton', 'tristen-newton', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-midnight', 'SM-TS', 1, 'Tristan da Silva', 'tristan-da-silva', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-midnight', 'SM-ZC', 1, 'Zach Collins', 'zach-collins', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-AN', 1, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-AT', 1, 'Adou Thiero', 'adou-thiero', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-BB', 1, 'Brooks Barnhizer', 'brooks-barnhizer', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-BS', 1, 'Ben Saraf', 'ben-saraf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-CC', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-CL', 1, 'Chaz Lanier', 'chaz-lanier', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-DH', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-DP', 1, 'Drake Powell', 'drake-powell', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-DW', 1, 'Danny Wolf', 'danny-wolf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-JB', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-JBR', 1, 'Johni Broome', 'johni-broome', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-JR', 1, 'Jase Richardson', 'jase-richardson', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-KB', 1, 'Koby Brea', 'koby-brea', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-KJ', 1, 'Kam Jones', 'kam-jones', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-KM', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-LM', 1, 'Liam McNeeley', 'liam-mcneeley', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-MP', 1, 'Micah Peavy', 'micah-peavy', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-RK', 1, 'Ryan Kalkbrenner', 'ryan-kalkbrenner', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-SJ', 1, 'Sion James', 'sion-james', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-WC', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-midnight', 'SMR-WR', 1, 'Will Riley', 'will-riley', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-midnight', 'TL-1', 1, 'LeBron James', 'lebron-james', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-midnight', 'TL-10', 1, 'Giannis Antetokounmpo', 'giannis-antetokounmpo', 'Milwaukee Bucks', 'milwaukee-bucks', '2025-26'),
  ('2025-26-topps-midnight', 'TL-11', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-midnight', 'TL-12', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-midnight', 'TL-13', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-midnight', 'TL-14', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-midnight', 'TL-15', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-midnight', 'TL-2', 1, 'Stephen Curry', 'stephen-curry', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-midnight', 'TL-3', 1, 'Anthony Edwards', 'anthony-edwards', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-midnight', 'TL-4', 1, 'Nikola Jokić', 'nikola-jokic', 'Denver Nuggets', 'denver-nuggets', '2025-26'),
  ('2025-26-topps-midnight', 'TL-5', 1, 'Shai Gilgeous-Alexander', 'shai-gilgeous-alexander', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-midnight', 'TL-6', 1, 'Tyrese Haliburton', 'tyrese-haliburton', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-midnight', 'TL-7', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-midnight', 'TL-8', 1, 'Kevin Durant', 'kevin-durant', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-midnight', 'TL-9', 1, 'Jayson Tatum', 'jayson-tatum', 'Boston Celtics', 'boston-celtics', '2025-26')
on conflict (set_id, card_code, slot) do update set
  player = excluded.player, player_id = excluded.player_id, team = excluded.team,
  team_id = excluded.team_id, season = excluded.season;

commit;
