-- =====================================================================
-- Hoops Archive -- migration 0003b5 : cartes 2025-26-topps-basketball (partie 5/5)
-- FICHIER GENERE AUTOMATIQUEMENT -- ne pas editer a la main.
-- Relancable sans risque (ON CONFLICT DO UPDATE).
-- =====================================================================

begin;

-- Cartes (97)
insert into public.cards (set_id, card_code, subset, player, team, player_id, team_id, season, rookie, variant, jersey_number) values
  ('2025-26-topps-basketball', 'TFRR-AB', 'TFRR', 'Ace Bailey', 'Utah Jazz', 'ace-bailey', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-AM', 'TFRR', 'Alijah Martin', 'Toronto Raptors', 'alijah-martin', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-AN', 'TFRR', 'Asa Newell', 'Atlanta Hawks', 'asa-newell', 'atlanta-hawks', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-AT', 'TFRR', 'Adou Thiero', 'Los Angeles Lakers', 'adou-thiero', 'los-angeles-lakers', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-BB', 'TFRR', 'Brooks Barnhizer', 'Oklahoma City Thunder', 'brooks-barnhizer', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-BS', 'TFRR', 'Ben Saraf', 'Brooklyn Nets', 'ben-saraf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-CB', 'TFRR', 'Collin Murray-Boyles', 'Toronto Raptors', 'collin-murray-boyles', 'toronto-raptors', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-CC', 'TFRR', 'Cedric Coward', 'Memphis Grizzlies', 'cedric-coward', 'memphis-grizzlies', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-CF', 'TFRR', 'Cooper Flagg', 'Dallas Mavericks', 'cooper-flagg', 'dallas-mavericks', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-CL', 'TFRR', 'Chaz Lanier', 'Detroit Pistons', 'chaz-lanier', 'detroit-pistons', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-DH', 'TFRR', 'Dylan Harper', 'San Antonio Spurs', 'dylan-harper', 'san-antonio-spurs', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-DP', 'TFRR', 'Drake Powell', 'Brooklyn Nets', 'drake-powell', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-DQ', 'TFRR', 'Derik Queen', 'New Orleans Pelicans', 'derik-queen', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-DW', 'TFRR', 'Danny Wolf', 'Brooklyn Nets', 'danny-wolf', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-ED', 'TFRR', 'Egor Dëmin', 'Brooklyn Nets', 'egor-demin', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-JB', 'TFRR', 'Joan Beringer', 'Minnesota Timberwolves', 'joan-beringer', 'minnesota-timberwolves', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-JO', 'TFRR', 'Johni Broome', 'Philadelphia 76ers', 'johni-broome', 'philadelphia-76ers', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-JR', 'TFRR', 'Jase Richardson', 'Orlando Magic', 'jase-richardson', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-JW', 'TFRR', 'Jamir Watkins', 'Washington Wizards', 'jamir-watkins', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-KB', 'TFRR', 'Koby Brea', 'Phoenix Suns', 'koby-brea', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-KJ', 'TFRR', 'Kasparas Jakučionis', 'Miami Heat', 'kasparas-jakucionis', 'miami-heat', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-KK', 'TFRR', 'Kon Knueppel', 'Charlotte Hornets', 'kon-knueppel', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-KM', 'TFRR', 'Khaman Maluach', 'Phoenix Suns', 'khaman-maluach', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-KO', 'TFRR', 'Kam Jones', 'Indiana Pacers', 'kam-jones', 'indiana-pacers', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-LM', 'TFRR', 'Liam McNeeley', 'Charlotte Hornets', 'liam-mcneeley', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-MP', 'TFRR', 'Micah Peavy', 'New Orleans Pelicans', 'micah-peavy', 'new-orleans-pelicans', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-MR', 'TFRR', 'Maxime Raynaud', 'Sacramento Kings', 'maxime-raynaud', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-NC', 'TFRR', 'Nique Clifford', 'Sacramento Kings', 'nique-clifford', 'sacramento-kings', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-NE', 'TFRR', 'Noa Essengue', 'Chicago Bulls', 'noa-essengue', 'chicago-bulls', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-NP', 'TFRR', 'Noah Penda', 'Orlando Magic', 'noah-penda', 'orlando-magic', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-NT', 'TFRR', 'Nolan Traore', 'Brooklyn Nets', 'nolan-traore', 'brooklyn-nets', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-RF', 'TFRR', 'Rasheer Fleming', 'Phoenix Suns', 'rasheer-fleming', 'phoenix-suns', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-RK', 'TFRR', 'Ryan Kalkbrenner', 'Charlotte Hornets', 'ryan-kalkbrenner', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-SJ', 'TFRR', 'Sion James', 'Charlotte Hornets', 'sion-james', 'charlotte-hornets', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-TP', 'TFRR', 'Tyrese Proctor', 'Cleveland Cavaliers', 'tyrese-proctor', 'cleveland-cavaliers', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-TS', 'TFRR', 'Thomas Sorber', 'Oklahoma City Thunder', 'thomas-sorber', 'oklahoma-city-thunder', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-WC', 'TFRR', 'Walter Clayton Jr.', 'Utah Jazz', 'walter-clayton-jr', 'utah-jazz', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-WR', 'TFRR', 'Will Riley', 'Washington Wizards', 'will-riley', 'washington-wizards', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TFRR-YH', 'TFRR', 'Yang Hansen', 'Portland Trail Blazers', 'yang-hansen', 'portland-trail-blazers', '2025-26', true, null, null),
  ('2025-26-topps-basketball', 'TNS-AC', 'TNS', 'Alex Caruso', 'Oklahoma City Thunder', 'alex-caruso', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-AH', 'TNS', 'Anfernee Hardaway', 'Orlando Magic', 'anfernee-hardaway', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-AM', 'TNS', 'Alonzo Mourning', 'Miami Heat', 'alonzo-mourning', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-AR', 'TNS', 'Kel''el Ware', 'Miami Heat', 'kelel-ware', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-ARE', 'TNS', 'Austin Reaves', 'Los Angeles Lakers', 'austin-reaves', 'los-angeles-lakers', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-AREE', 'TNS', 'Antonio Reeves', 'New Orleans Pelicans', 'antonio-reeves', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-BSC', 'TNS', 'Baylor Scheierman', 'Boston Celtics', 'baylor-scheierman', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-CJ', 'TNS', 'Colby Jones', 'Washington Wizards', 'colby-jones', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-CK', 'TNS', 'Corey Kispert', 'Washington Wizards', 'corey-kispert', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-CL', 'TNS', 'Christian Laettner', 'Minnesota Timberwolves', 'christian-laettner', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-DB', 'TNS', 'Desmond Bane', 'Memphis Grizzlies', 'desmond-bane', 'memphis-grizzlies', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-DG', 'TNS', 'Daniel Gafford', 'Dallas Mavericks', 'daniel-gafford', 'dallas-mavericks', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-DR', 'TNS', 'David Robinson', 'San Antonio Spurs', 'david-robinson', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-DW', 'TNS', 'Deron Williams', 'Utah Jazz', 'deron-williams', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-HI', 'TNS', 'Harrison Ingram', 'San Antonio Spurs', 'harrison-ingram', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-IQ', 'TNS', 'Immanuel Quickley', 'Toronto Raptors', 'immanuel-quickley', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-IS', 'TNS', 'Isaiah Stewart', 'Detroit Pistons', 'isaiah-stewart', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-JF', 'TNS', 'Johnny Furphy', 'Indiana Pacers', 'johnny-furphy', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-JG', 'TNS', 'Jeff Green', 'Houston Rockets', 'jeff-green', 'houston-rockets', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-JH', 'TNS', 'Juwan Howard', 'Washington Wizards', 'juwan-howard', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-JK', 'TNS', 'Jason Kidd', 'Phoenix Suns', 'jason-kidd', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-JT', 'TNS', 'Jaylon Tyson', 'Cleveland Cavaliers', 'jaylon-tyson', 'cleveland-cavaliers', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-JW', 'TNS', 'Jalen Wilson', 'Brooklyn Nets', 'jalen-wilson', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-KG', 'TNS', 'Kyshawn George', 'Washington Wizards', 'kyshawn-george', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-KM', 'TNS', 'Kris Murray', 'Portland Trail Blazers', 'kris-murray', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-LJ', 'TNS', 'Larry Johnson', 'Charlotte Hornets', 'larry-johnson', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-LM', 'TNS', 'Leonard Miller', 'Minnesota Timberwolves', 'leonard-miller', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-OT', 'TNS', 'Obi Toppin', 'Indiana Pacers', 'obi-toppin', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-PB', 'TNS', 'Paolo Banchero', 'Orlando Magic', 'paolo-banchero', 'orlando-magic', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-PW', 'TNS', 'Patrick Williams', 'Chicago Bulls', 'patrick-williams', 'chicago-bulls', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-RD', 'TNS', 'Ryan Dunn', 'Phoenix Suns', 'ryan-dunn', 'phoenix-suns', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-RJ', 'TNS', 'Richard Jefferson', 'Brooklyn Nets', 'richard-jefferson', 'brooklyn-nets', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-RP', 'TNS', 'Robert Parish', 'Boston Celtics', 'robert-parish', 'boston-celtics', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-TH', 'TNS', 'Tim Hardaway Jr.', 'Detroit Pistons', 'tim-hardaway-jr', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-TJ', 'TNS', 'Trayce Jackson-Davis', 'Golden State Warriors', 'trayce-jackson-davis', 'golden-state-warriors', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-TK', 'TNS', 'Tyler Kolek', 'New York Knicks', 'tyler-kolek', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-TS', 'TNS', 'Terrence Shannon Jr.', 'Minnesota Timberwolves', 'terrence-shannon-jr', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'TNS-WK', 'TNS', 'Walker Kessler', 'Utah Jazz', 'walker-kessler', 'utah-jazz', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-AS', 'WW', 'Alex Sarr', 'Washington Wizards', 'alex-sarr', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-BC', 'WW', 'Bilal Coulibaly', 'Washington Wizards', 'bilal-coulibaly', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-BM', 'WW', 'Brandon Miller', 'Charlotte Hornets', 'brandon-miller', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-DJ', 'WW', 'Dillon Jones', 'Oklahoma City Thunder', 'dillon-jones', 'oklahoma-city-thunder', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-GD', 'WW', 'Gradey Dick', 'Toronto Raptors', 'gradey-dick', 'toronto-raptors', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-JC', 'WW', 'Jaylen Clark', 'Minnesota Timberwolves', 'jaylen-clark', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-JF', 'WW', 'Johnny Furphy', 'Indiana Pacers', 'johnny-furphy', 'indiana-pacers', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-JJ', 'WW', 'Jaime Jaquez Jr.', 'Miami Heat', 'jaime-jaquez-jr', 'miami-heat', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-JW', 'WW', 'Jordan Hawkins', 'New Orleans Pelicans', 'jordan-hawkins', 'new-orleans-pelicans', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-KB', 'WW', 'Kobe Brown', 'Los Angeles Clippers', 'kobe-brown', 'los-angeles-clippers', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-KG', 'WW', 'Kyshawn George', 'Washington Wizards', 'kyshawn-george', 'washington-wizards', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-KM', 'WW', 'Kris Murray', 'Portland Trail Blazers', 'kris-murray', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-LM', 'WW', 'Leonard Miller', 'Minnesota Timberwolves', 'leonard-miller', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-NS', 'WW', 'Nick Smith Jr.', 'Charlotte Hornets', 'nick-smith-jr', 'charlotte-hornets', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-PD', 'WW', 'Pacôme Dadiet', 'New York Knicks', 'pacome-dadiet', 'new-york-knicks', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-RD', 'WW', 'Rob Dillingham', 'Minnesota Timberwolves', 'rob-dillingham', 'minnesota-timberwolves', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-RH', 'WW', 'Ron Holland II', 'Detroit Pistons', 'ron-holland-ii', 'detroit-pistons', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-SC', 'WW', 'Stephon Castle', 'San Antonio Spurs', 'stephon-castle', 'san-antonio-spurs', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-SH', 'WW', 'Scoot Henderson', 'Portland Trail Blazers', 'scoot-henderson', 'portland-trail-blazers', '2025-26', false, null, null),
  ('2025-26-topps-basketball', 'WW-VW', 'WW', 'Victor Wembanyama', 'San Antonio Spurs', 'victor-wembanyama', 'san-antonio-spurs', '2025-26', false, null, null)
on conflict (set_id, card_code) do update set
  subset = excluded.subset, player = excluded.player, team = excluded.team,
  player_id = excluded.player_id, team_id = excluded.team_id, season = excluded.season,
  rookie = excluded.rookie, variant = excluded.variant, jersey_number = excluded.jersey_number;

-- Associations carte/joueur (97)
insert into public.card_players (set_id, card_code, slot, player, player_id, team, team_id, season) values
  ('2025-26-topps-basketball', 'TFRR-AB', 1, 'Ace Bailey', 'ace-bailey', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-AM', 1, 'Alijah Martin', 'alijah-martin', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-AN', 1, 'Asa Newell', 'asa-newell', 'Atlanta Hawks', 'atlanta-hawks', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-AT', 1, 'Adou Thiero', 'adou-thiero', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-BB', 1, 'Brooks Barnhizer', 'brooks-barnhizer', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-BS', 1, 'Ben Saraf', 'ben-saraf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-CB', 1, 'Collin Murray-Boyles', 'collin-murray-boyles', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-CC', 1, 'Cedric Coward', 'cedric-coward', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-CF', 1, 'Cooper Flagg', 'cooper-flagg', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-CL', 1, 'Chaz Lanier', 'chaz-lanier', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-DH', 1, 'Dylan Harper', 'dylan-harper', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-DP', 1, 'Drake Powell', 'drake-powell', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-DQ', 1, 'Derik Queen', 'derik-queen', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-DW', 1, 'Danny Wolf', 'danny-wolf', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-ED', 1, 'Egor Dëmin', 'egor-demin', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-JB', 1, 'Joan Beringer', 'joan-beringer', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-JO', 1, 'Johni Broome', 'johni-broome', 'Philadelphia 76ers', 'philadelphia-76ers', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-JR', 1, 'Jase Richardson', 'jase-richardson', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-JW', 1, 'Jamir Watkins', 'jamir-watkins', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-KB', 1, 'Koby Brea', 'koby-brea', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-KJ', 1, 'Kasparas Jakučionis', 'kasparas-jakucionis', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-KK', 1, 'Kon Knueppel', 'kon-knueppel', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-KM', 1, 'Khaman Maluach', 'khaman-maluach', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-KO', 1, 'Kam Jones', 'kam-jones', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-LM', 1, 'Liam McNeeley', 'liam-mcneeley', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-MP', 1, 'Micah Peavy', 'micah-peavy', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-MR', 1, 'Maxime Raynaud', 'maxime-raynaud', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-NC', 1, 'Nique Clifford', 'nique-clifford', 'Sacramento Kings', 'sacramento-kings', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-NE', 1, 'Noa Essengue', 'noa-essengue', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-NP', 1, 'Noah Penda', 'noah-penda', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-NT', 1, 'Nolan Traore', 'nolan-traore', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-RF', 1, 'Rasheer Fleming', 'rasheer-fleming', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-RK', 1, 'Ryan Kalkbrenner', 'ryan-kalkbrenner', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-SJ', 1, 'Sion James', 'sion-james', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-TP', 1, 'Tyrese Proctor', 'tyrese-proctor', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-TS', 1, 'Thomas Sorber', 'thomas-sorber', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-WC', 1, 'Walter Clayton Jr.', 'walter-clayton-jr', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-WR', 1, 'Will Riley', 'will-riley', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-basketball', 'TFRR-YH', 1, 'Yang Hansen', 'yang-hansen', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-AC', 1, 'Alex Caruso', 'alex-caruso', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-AH', 1, 'Anfernee Hardaway', 'anfernee-hardaway', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-AM', 1, 'Alonzo Mourning', 'alonzo-mourning', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-AR', 1, 'Kel''el Ware', 'kelel-ware', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-ARE', 1, 'Austin Reaves', 'austin-reaves', 'Los Angeles Lakers', 'los-angeles-lakers', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-AREE', 1, 'Antonio Reeves', 'antonio-reeves', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-BSC', 1, 'Baylor Scheierman', 'baylor-scheierman', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-CJ', 1, 'Colby Jones', 'colby-jones', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-CK', 1, 'Corey Kispert', 'corey-kispert', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-CL', 1, 'Christian Laettner', 'christian-laettner', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-DB', 1, 'Desmond Bane', 'desmond-bane', 'Memphis Grizzlies', 'memphis-grizzlies', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-DG', 1, 'Daniel Gafford', 'daniel-gafford', 'Dallas Mavericks', 'dallas-mavericks', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-DR', 1, 'David Robinson', 'david-robinson', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-DW', 1, 'Deron Williams', 'deron-williams', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-HI', 1, 'Harrison Ingram', 'harrison-ingram', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-IQ', 1, 'Immanuel Quickley', 'immanuel-quickley', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-IS', 1, 'Isaiah Stewart', 'isaiah-stewart', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-JF', 1, 'Johnny Furphy', 'johnny-furphy', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-JG', 1, 'Jeff Green', 'jeff-green', 'Houston Rockets', 'houston-rockets', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-JH', 1, 'Juwan Howard', 'juwan-howard', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-JK', 1, 'Jason Kidd', 'jason-kidd', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-JT', 1, 'Jaylon Tyson', 'jaylon-tyson', 'Cleveland Cavaliers', 'cleveland-cavaliers', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-JW', 1, 'Jalen Wilson', 'jalen-wilson', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-KG', 1, 'Kyshawn George', 'kyshawn-george', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-KM', 1, 'Kris Murray', 'kris-murray', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-LJ', 1, 'Larry Johnson', 'larry-johnson', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-LM', 1, 'Leonard Miller', 'leonard-miller', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-OT', 1, 'Obi Toppin', 'obi-toppin', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-PB', 1, 'Paolo Banchero', 'paolo-banchero', 'Orlando Magic', 'orlando-magic', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-PW', 1, 'Patrick Williams', 'patrick-williams', 'Chicago Bulls', 'chicago-bulls', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-RD', 1, 'Ryan Dunn', 'ryan-dunn', 'Phoenix Suns', 'phoenix-suns', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-RJ', 1, 'Richard Jefferson', 'richard-jefferson', 'Brooklyn Nets', 'brooklyn-nets', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-RP', 1, 'Robert Parish', 'robert-parish', 'Boston Celtics', 'boston-celtics', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-TH', 1, 'Tim Hardaway Jr.', 'tim-hardaway-jr', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-TJ', 1, 'Trayce Jackson-Davis', 'trayce-jackson-davis', 'Golden State Warriors', 'golden-state-warriors', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-TK', 1, 'Tyler Kolek', 'tyler-kolek', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-TS', 1, 'Terrence Shannon Jr.', 'terrence-shannon-jr', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-basketball', 'TNS-WK', 1, 'Walker Kessler', 'walker-kessler', 'Utah Jazz', 'utah-jazz', '2025-26'),
  ('2025-26-topps-basketball', 'WW-AS', 1, 'Alex Sarr', 'alex-sarr', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-basketball', 'WW-BC', 1, 'Bilal Coulibaly', 'bilal-coulibaly', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-basketball', 'WW-BM', 1, 'Brandon Miller', 'brandon-miller', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-basketball', 'WW-DJ', 1, 'Dillon Jones', 'dillon-jones', 'Oklahoma City Thunder', 'oklahoma-city-thunder', '2025-26'),
  ('2025-26-topps-basketball', 'WW-GD', 1, 'Gradey Dick', 'gradey-dick', 'Toronto Raptors', 'toronto-raptors', '2025-26'),
  ('2025-26-topps-basketball', 'WW-JC', 1, 'Jaylen Clark', 'jaylen-clark', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-basketball', 'WW-JF', 1, 'Johnny Furphy', 'johnny-furphy', 'Indiana Pacers', 'indiana-pacers', '2025-26'),
  ('2025-26-topps-basketball', 'WW-JJ', 1, 'Jaime Jaquez Jr.', 'jaime-jaquez-jr', 'Miami Heat', 'miami-heat', '2025-26'),
  ('2025-26-topps-basketball', 'WW-JW', 1, 'Jordan Hawkins', 'jordan-hawkins', 'New Orleans Pelicans', 'new-orleans-pelicans', '2025-26'),
  ('2025-26-topps-basketball', 'WW-KB', 1, 'Kobe Brown', 'kobe-brown', 'Los Angeles Clippers', 'los-angeles-clippers', '2025-26'),
  ('2025-26-topps-basketball', 'WW-KG', 1, 'Kyshawn George', 'kyshawn-george', 'Washington Wizards', 'washington-wizards', '2025-26'),
  ('2025-26-topps-basketball', 'WW-KM', 1, 'Kris Murray', 'kris-murray', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-basketball', 'WW-LM', 1, 'Leonard Miller', 'leonard-miller', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-basketball', 'WW-NS', 1, 'Nick Smith Jr.', 'nick-smith-jr', 'Charlotte Hornets', 'charlotte-hornets', '2025-26'),
  ('2025-26-topps-basketball', 'WW-PD', 1, 'Pacôme Dadiet', 'pacome-dadiet', 'New York Knicks', 'new-york-knicks', '2025-26'),
  ('2025-26-topps-basketball', 'WW-RD', 1, 'Rob Dillingham', 'rob-dillingham', 'Minnesota Timberwolves', 'minnesota-timberwolves', '2025-26'),
  ('2025-26-topps-basketball', 'WW-RH', 1, 'Ron Holland II', 'ron-holland-ii', 'Detroit Pistons', 'detroit-pistons', '2025-26'),
  ('2025-26-topps-basketball', 'WW-SC', 1, 'Stephon Castle', 'stephon-castle', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26'),
  ('2025-26-topps-basketball', 'WW-SH', 1, 'Scoot Henderson', 'scoot-henderson', 'Portland Trail Blazers', 'portland-trail-blazers', '2025-26'),
  ('2025-26-topps-basketball', 'WW-VW', 1, 'Victor Wembanyama', 'victor-wembanyama', 'San Antonio Spurs', 'san-antonio-spurs', '2025-26')
on conflict (set_id, card_code, slot) do update set
  player = excluded.player, player_id = excluded.player_id, team = excluded.team,
  team_id = excluded.team_id, season = excluded.season;

commit;
